---
title: IPOO - Cap. 5 Comportamento Mais Sofisticado
subtitle: Aula 5.3 - Prática
---

# Comparando uso de ArrayList e HashMap {background-color="#40666e"}

##

No capítulo anterior, fizemos um exercício que tratava do **estoque de produtos**.

- Os produtos eram guardados em um `ArrayList`.
- E, em várias situações, precisávamos encontrar um produto pelo seu identificador.

. . .

Repare que, nesse contexto, podemos tratar a coleção de produtos como **pares de objetos identificador-produto**.

- Ou seja, como **pares de objetos chave-valor**.
- Que é justamente o que um `HashMap` faz.
- Portanto, nos exercícios a seguir vamos alterar o projeto para trabalhar com `HashMap` em vez de `ArrayList`.

##

::: {.callout-note title="Exercício 1" icon=false}
::: {.nonincremental}
Baixe o projeto `produtos` que você entregou como exercício na aula prática do capítulo anterior e renomeie 
a pasta do projeto para `produtos-com-hashmap`.

Altere o projeto substituindo o uso de `ArrayList` por `HashMap`.

- Como citado no slide anterior, a ideia é que o `HashMap` guarde entradas tendo o identificador do produto como chave e o produto como valor.
- Planeje as alterações a serem feitas antes de realmente alterar o código.
- Pense em como a implementação pode ser feita com o mínimo de alterações.

Teste suas alterações (teste todos os métodos que tinha implementado)!
:::
:::

##

::: {.callout-note title="Exercício 2" icon=false}
::: {.nonincremental}
Confira como você tratou a versão sobrecarregada do método `encontrarProduto` que recebe o ID do produto por parâmetro.

Lembre-se que, usando um HashMap, você não deve fazer um loop para encontrar o produto pelo ID. 
Você deve usar o método `get` para encontrar o produto (valor) a partir do ID (chave).
:::
::: 

##

::: {.callout-note title="Exercício 3" icon=false}
::: {.nonincremental}
Compare o código do projeto `produtos` com o código do projeto `produtos-com-hashmap`.

Você viu alguma vantagem em utilizar `HashMap` em vez de `ArrayList`?

- Se você tivesse começando o projeto do zero, você acha que seria melhor usar `HashMap` desde o início? Por quê?

Escreva sua resposta no comentário `javadoc` da classe `GerenciadorDeEstoque` do projeto `produtos-com-hashmap`.
:::
:::

## 

No projeto `produtos-com-hashmap`, como você tratou a versão sobrecarregada do método `encontrarProduto` que recebe **o nome do produto** por parâmetro?

- Provavelmente, você implementou um loop para percorrer as chaves do `HashMap` e verificou o nome do produto, certo?
- Você acha que existe alguma forma mais eficiente de fazer isso?

. . .

Pense sobre isso antes de continuar.

## 

Repare que quando usamos um `HashMap`, se quisermos encontrar um valor a partir de uma chave, nós **não precisamos** implementar **um loop**.

- Nós podemos simplesmente usar o método `get`.

. . .

É interessante que você saiba que isso não é apenas uma questão de ficar mais fácil para implementar.

- Um ponto **importante** é que o método `get` de um `HashMap` **é muito mais eficiente** (ou seja, mais rápido) do que um loop que percorre todos os elementos de uma coleção.
  - Pense, por exemplo, em um estoque com milhares de produtos.

##

O método `get` do `HashMap` é  mais eficiente porque usa uma estrutura de dados chamada **tabela Hash** 

- que otimiza a busca de valores a partir de chaves.

. . .

Você aprenderá sobre isso na **disciplina de Estrutura de Dados**.

- Mas, por enquanto, basta que saiba que um programa será mais rápido se usar `get` de `HashMap` em vez de um loop em um `ArrayList`, por exemplo.


## 

Sabendo disso, como você poderia implementar, de forma mais eficiente, o método `encontrarProduto` que recebe o nome do produto por parâmetro?

- Pense um pouco antes de continuar.

. . .

Você talvez tenha pensado que se tivermos um `HashMap` que use o nome do produto como chave e o produto como valor,

- poderíamos simplesmente usar o método `get` do `HashMap` para encontrar o produto.
- O que tornaria a busca mais rápida.

##

Mas se substituirmos o `HashMap` que temos até agora, que usa o identificador como chave, 

- teríamos que voltar a fazer um loop na outra versão do método `encontrarProduto` que recebe o identificador por parâmetro.

. . .

O que poderíamos fazer então?

## 

A solução nesse caso seria ter dois objetos `HashMap`:

- Um que use o identificador como chave e outro que use o nome do produto como chave.
- Assim, poderíamos usar um `HashMap` para buscar produtos pelo identificador e outro para buscar pelo nome.

. . .

Repare que essa é uma **solução de compromisso** (_trade-off_).

- Nós estamos usando mais memória do computador (para guardar um segundo `HashMap`).
- Mas com a vantagem de tornar nosso programa mais eficiente (mais rápido).

##

Em um sistema com muitos produtos, a diferença de eficiência pode ser significativa.

- E é importante ressaltar que os objetos não são duplicados na memória por usarmos dois hashmaps.
- Já que os HashMaps guardam ponteiros para os objetos.
  - E, portanto, o uso adicional de memória não é tão grande.

##

::: {.callout-note title="Exercício 4" icon=false}
::: {.nonincremental}
Altere o projeto `produtos-com-hashmap` para que ele tenha dois objetos   `HashMap`:

- Um que use o identificador como chave e outro que use o nome do produto como chave.
- Altere o método `encontrarProduto` que recebe o nome do produto por parâmetro para usar o `HashMap` que usa o nome do produto como chave.
- E, claro, lembre-se de tratar o segundo `HashMap` no método `adicionarProduto`.

Teste suas alterações!
:::
:::

# Analisador de Logs Web {background-color="#40666e"}

##

Servidores web geralmente guardam arquivos de log de acesso às suas páginas.

- Usando ferramentas adequadas, esses logs permitem extrair e analisar informações úteis como:
  - quais são as páginas mais acessadas
  - de quais sites vieram o acesso a este site
  - se outros sites parecem ter links quebrados para o site
  - a quantidade de dados que são enviados para quem acessa
  - o períodos mais ocupados do servidor (com mais acessos)
    - ao longo de um dia, um mês ou um ano.

##

Essas informações ajudam os administradores do sistema a decidir, por exemplo:

- Se eles precisam de máquinas mais poderosas como servidor,
- ou quais são os horários com menor acesso para fazer uma manutenção.

##

O projeto [`analisador-logs-web`](https://github.com/ufla-ipoo/analisador-logs-web) 
tem uma aplicação que faz uma análise de dados de um servidor web.

- O servidor escreve uma linha de log no arquivo a cada acesso feito.
- A linha tem dados do momento do acesso, no formato:

  `ano mes dia hora minuto`

- Por exemplo, um acesso às 16:35h no dia 25 de setembro de 2026, é representado como:

  `2026 09 25 16 35`

##

A versão atual do projeto permite analisar qual hora do dia, em média,
o servidor tende a ficar mais ocupado (ou menos ocupado).

- Isso é feito contando a quantidade de acessos feitos a cada hora a partir do arquivo de log.
- Uma amostra do arquivo de log do servidor está presente no arquivo `weblog.txt`.

## 

Abra o projeto `analisador-logs-web` e leia o código da classe `AnalisadorDeLog`.

- Veja que a classe tem um atributo que é um array (vetor) de inteiros.

. . .

Lembre-se que o material sobre uso de arrays em Java foi apresentado como estudo
para casa na Aula 4.3.

- Se você ainda não estudou esse material, você deve agora parar, acessar o material
  da aula e procurar a seção **Coleções de tamanho fixo**.
- Ao terminar, volte para continuar as atividades dessa aula.

##


Teste o programa do projeto `analisador-logs-web`, fazendo o seguinte:

- crie um objeto da classe `AnalisadorDeLog`,
- chame o método `analisarDadosPorHora`
- e, em seguida, chame o método `imprimirContagensPorHora`.

. . .

Qual é o horário mais ocupado do dia?

## {auto-animate=true}

A classe `LeitorDeArquivoDeLog` é bastante complexa e sugiro que você não gaste muito tempo investigando sua implementação. 

- Sua função é lidar com a tarefa de dividir cada linha de log em valores de dados separados, 
- mas podemos abstrair os detalhes da implementação considerando apenas os cabeçalhos de dois de seus métodos:

. . .

::: {.halfincfontsize}
```{.java code-line-numbers="false"}
public boolean hasNext()
public EntradaDeLog next()
```
:::

## {auto-animate=true}

::: {.halfincfontsize}
```{.java code-line-numbers="false"}
public boolean hasNext()
public EntradaDeLog next()
```
:::

Esses métodos correspondem exatamente aos que vimos com o tipo `Iterator`, 

- e um `LeitorDeArquivoDeLog` pode ser usado exatamente da mesma maneira, 
- exceto que não é permitido o uso do método `remove`. 

##

Para cada `EntradaDeLog`, o método `analisarDadosPorHora` do analisador obtém o valor do atributo `hora`:

::: {.halfincfontsize}
```{.java code-line-numbers="false"}
int hora = entrada.obterHora();
```
:::

. . .

Sabemos que o valor armazenado na variável local `hora` estará sempre no intervalo de 0 a 23,

- o que corresponde exatamente ao intervalo válido de índices para o vetor `contagensPorHora`. 
- Portanto, cada vez que um valor de hora é lido, desejamos atualizar a contagem para essa hora em 1, usando:

. . .

::: {.halfincfontsize}
```{.java code-line-numbers="false"}
contagensPorHora[hora]++;
```
:::

##

Ao final do método `analisarDadosPorHora`, 

- temos um conjunto completo de contagens cumulativas para cada hora do período de registro.

. . .

Já o método `imprimirContagensPorHora` usa um loop `for` tradicional (com contador) para exibir as informações do vetor.

##

::: {.callout-note title="Exercício 5" icon=false}
::: {.nonincremental}
Altere a classe `AnalisadorDeLog` criando um construtor sobrecarregado que recebe por parâmetro
o nome do arquivo de log a ser analisado.
Será necessário passar o nome do arquivo para o construtor da classe `LeitorDeArquivoDeLog`.

Para testar, use a classe `GeradorArquivoDeLog` para criar seu próprio arquivo de log de entradas aleatórias,
e analise os dados desse arquivo.
:::
::: 

##

::: {.callout-note title="Exercício 6" icon=false}
::: {.nonincremental}
Crie um método `numeroDeAcessos` na classe `AnalisadorDeLog` que retorna a quantidade total de
acessos armazenados em um arquivo de log.

O método **deve** fazer o cálculo percorrendo (iterando) o vetor `contagensPorHora`.

Dica: para testar seu método, use o gerador para criar um arquivo com poucas entradas, e o utilize
na análise de forma que você consiga conferir manualmente se o resultado está correto.
:::
::: 

##

::: {.callout-note title="Exercício 7" icon=false}
::: {.nonincremental}
Adicione um método `horaMaisOcupada` na classe `AnalisadorDeLog` que retorna a hora com a **maior**
quantidade de acessos.

É necessário verificar todos os elementos do vetor `contagensPorHora`? 
Em caso afirmativo, qual é o tipo de loop mais adequado para fazer a implementação?
:::
::: 

. . .

::: {.callout-note title="Exercício 8" icon=false}
::: {.nonincremental}
Adicione um método `horaMaisTranquila` na classe `AnalisadorDeLog` que retorna a hora com a **menor**
quantidade de acessos.

Dica: lembre-se de testar um caso no qual toda as horas possuem algum acesso (ou seja, um valor diferente de zero).
:::
::: 

##

::: {.callout-note title="Exercício 9" icon=false}
::: {.nonincremental}
Adicione um método `duasHorasSeguidasMaisOcupadas` na classe `AnalisadorDeLog` que retorna o período de duas horas **consecutivas**
com a **maior** quantidade de acessos.

O método deve retornar a hora de início do período em questão.

Exemplo: se as duas horas consecutivas mais ocupadas são de 10h às 12h (correspondente às horas 10 e 11),
 o método deve retornar 10.
:::
::: 

##

::: {.callout-note title="Exercício 10 - [Desafio]{.alert}" icon=false}
::: {.nonincremental}
Vamos melhorar o projeto para permitir também a análise de acessos por dia da semana, e não apenas por hora.

A ideia é que consigamos saber:

- A quantidade de acessos de cada dia da semana.
- O dia da semana com a maior quantidade de acessos.
- O dia da semana com a menor quantidade de acessos.

Dicas: 

1. Você precisará criar método de acesso na classe `EntradaDeLog` que retorne o dia da semana 
no qual aquele acesso foi feito.
  - Pesquisa na internet como o atributo constante, público e estático `DAY_OF_WEEK` da classe `Calendar`
pode ser usado na sua implementação.
2. Você precisará guardar as informações também por dia da semana na classe `AnalisadorDeLog`.
   Para isso é melhor usar vetor, `ArrayList` ou `HashMap`?
:::
::: 