---
title: IPOO - Cap. 5 Comportamento Mais Sofisticado
subtitle: Aula 5.2 - Teórica
---

# Usando um mapa no sistema de suporte {background-color="#40666e"}

## {.smaller}

Na aula passada você fez um exercício para que o sistema de suporte desse respostas que tivessem relação com a reclamação do usuário.

```{.java code-line-numbers="false"}
    if (entrada.contains("lento")) {
        return "Acredito que isso tem a ver com o seu hardware. " +
               "Atualizar seu processador deve resolver todos os " +
               "problemas de desempenho. Você tem algum problema " + 
               "com nosso software?"
    }
    else if (entrada.contains("bug")) {
        ...
``` 

. . .

Mas tratar isso usando blocos `if\else if` não é a melhor forma implementar.

- Isso porque a cada nova palavra-chave tratada, teríamos que alterar o código e recompilar o sistema.




# Conjuntos (`sets`) {background-color="#40666e"}

## {.smaller}

A biblioteca de classes do Java possui diferentes tipos de [conjuntos](.alert) implementados em diferentes classes.

- Uma delas é a classe `HashSet`.

. . .


::: {.callout-note title="Exercício" icon=false}
Busque na documentação do Java, ou em outras fontes, quais são as similaridades e as diferenças enre
um `HashSet` e um `ArrayList`.

Tente entender porque `ArrayList` é um caso especial de `List` e `HashSet` é um caso especial de `Set`.
:::

## {.smaller}

A declaração de um `HashSet`, a criação do objeto e a adição de elementos é feita da mesma forma que um `ArrayList`.

::: {.halfincfontsize}
```{.java code-line-numbers="false"}
    import java.util.HashSet;
    . . .
    HashSet<String> conjunto = new HashSet<>();
    conjunto.add("um");
    conjunto.add("dois");
    conjunto.add("três");
```
:::

. . . 

Para percorrer um `HashSet` podemos usar um for-each, igualzinho ao que usamos para `ArrayList`.

::: {.halfincfontsize}
```{.java code-line-numbers="false"}
    for(String elemento : conjunto) {
        // faz alguma coisa com o elemento.
    }
```
:::

## {.smaller}

Repare, portanto, que **usar diferentes coleções** em Java **é** sempre **muito parecido**.

- Se você entender como usar uma delas, você conseguirá usar as outras com facilidade.

. . .

As **diferenças** entre as coleções **estão nos** seus **comportamentos**.

- Uma lista, por exemplo, mantém a ordem dos elementos, permite acesso aos elementos por posição, e permite elementos repetidos.
- Já um conjunto não mantém a ordem dos elementos, e garante que não existem elementos repetidos.
  - Portanto, os elementos podem ser percorridos no for-each em ordem diferente da que eles foram inseridos.
  - E inserir um mesmo elemento uma segunda vez, simplesmente não tem nenhum efeito.


# Escrevendo documentação de classes {background-color="#40666e"}

## {.smaller}

Quando estamos trabalhando em nossos projetos, 

- é importante escrevermos a **documentação de nossas classes**, à medida que desenvolvemos o código.

- Muitas vezes programadores não levam a sério a documentação, o que pode levar a sérios problemas.

. . .

Se você não fornecer documentação suficiente, pode ser difícil para outro programador entender suas classes.

- Muitas vezes esse outro programador pode ser você mesmo :)

. . .

Sem documentação, precisamos ler o código da classe para tentar entender como ela funciona.

- Isso pode funcionar em um projeto pequeno de estudante.
- Mas cria problemas em projetos do mundo real.

## {.smaller}

É muito comum que sistemas comerciais tenham centenas de milhares de linhas de código.

- Imagine que você tivesse que ler todas essas linhas para entender como o código funciona.
- Seria impossível!

. . . 

Nós conseguimos usar as classes da biblioteca Java, como `HashSet` e `Random`, olhando apenas a documentação delas.

- Nós nunca precisamos olhar o código-fonte destas classes.

. . . 

Isso funciona porque as classes estão suficientemente bem documentadas.

- Seria muito mais difícil usar essas classes, se precisássemos ler e entender o código-fonte delas primeiro.

## {.smaller}

Em uma equipe de desenvolvimento de software, a implementação das classes é geralmente dividida entre vários programadores.

- Um programador poderia implementar a classe `SistemaDeSuporte`, por exemplo, e outro a classe `LeitorDeEntrada`.
- Portanto, você pode precisar implementar uma classe enquanto chama métodos de outras classes.

. . .

Assim, o mesmo argumento usado para as classes da biblioteca Java vale para as classes que você escreve.

- Se podemos usar as classes sem ter que ler e entender toda a implementação, nossa tarefa fica mais fácil.
- Nós precisamos apenas da interface das classes e não da implementação.
- Portanto, precisamos escrever boa documentação de classes também para as nossas próprias classes.

## {.smaller}

::: {.callout-tip title="Conceito" icon=false}
A **documentação** de uma classe deve ser detalhada o suficiente para que outros programadores
consigam usar a classe sem precisar ler o código fonte.
:::

. . .

O Java tem uma ferramenta chamada [javadoc](.alert) que gera documentação a partir de comentários no código.

- Toda a documentação oficial das classes da biblioteca Java é gerada com o javadoc.

. . .

O BlueJ usa o javadoc para gerar documentação das classes.

- Com o código de uma classe aberto no BlueJ, podemos acessar a caixa de opções no canto superior direito e mudar de _código-fonte_ para _documentação_.

- Ou podemos também usar o menu `Ferramentas` &rarr; `Documentaçao do Projeto` para gerar a documentação de todas as classes do projeto.

##

::: {.callout-note title="Exercício" icon=false}
Experimente acessar a documentação da classe `SistemaDeSuporte` no BlueJ.
:::

. . .

::: {.fontsize70}
Os arquivos HTML gerados ficam em uma pasta `doc` dentro do projeto e podem ser abertos em qualquer navegador.
:::

## {.smaller}

A **documentação de uma classe** deveria incluir, no mínimo:

- O nome da classe.
- Um comentário descrevendo o objetivo e as características da classe.
- Um número de versão.
- O nome do(s) autor(es).
- Documentação para cada construtor e para cada método.

## {.smaller}

A **documentação de todo construtor e método** deve incluir, no mínimo:

- O nome do método.
- O tipo de retorno.
- Os nomes e tipos dos parâmetros.
- Uma descrição do objetivo e função do método.
- Uma descrição de cada parâmetro.
- Uma descrição do valor retornado.

. . .

Além disso, cada projeto deveria ter um comentário geral sobre o projeto.

- Geralmente dentro de um arquivo `README` na pasta raiz do projeto.
- No BlueJ podemos fazer esse comentário de projeto abrindo o arquivo que fica no 
canto superior esquerdo do diagrama de classses. 

## {.smaller}

Alguns elementos da documentação podem ser sempre extraídos do código-fonte.

- Como os nomes e parâmetros dos métodos, por exemplo.
- Já a descrição da classe e dos métodos demanda mais atenção já que pode ser facilmente esquecida, ou ficar incompleta.

. . .

No Java, comentários `Javadoc` são escritos com um símbolo especial de comentário.

::: {.halfincfontsize}
```{.java code-line-numbers="false"}
/**
 * Este é um comentário Javadoc.
 * Ele pode ter várias linhas.
 */
```
:::

## {.smaller}

O comentário deve ter `/**` no início e `*/` no final para ser reconhecido como um comentário `javadoc`.

- Se o comentário vem imediatamente antes da declaração da classe, ele é lido como a descrição da classe.
- Se ele está logo acima de uma assinatura de método, é considerado como um comentário do método.

. . .

Como exatamente o comentário deve ser formatado para gerar a documentação pode variar de acordo com as
ferramentas de cada linguagem de programação.

. . .

No caso do `javadoc` várias palavras-chave especiais estão disponíveis para formatar a documentação.

- Essas chaves começam com `@`, como, por exemplo:
  - `@version`
  - `@author`
  - `@param`
  - `@return`

## 

::: {.callout-note title="Exercício" icon=false}
Encontre exemplos de palavras-chave `javadoc` no projeto do sistema de suporte e 
verifique como eles influenciam a formatação da documentação.

Experimente fazer alterações e conferir o resultado na documentação gerada.
:::

::: {.callout-note title="Exercício [(entrega)]{.alert}" icon=false}
::: {.nonincremental}
Documente adequadamente as classes do projeto de suporte técnico e gere a documentação
usando o BlueJ.

Confira se a documentação gerada está completa antes de enviar o projeto.
:::
:::


# Entregas dessa Aula {background-color="#40666e"}

## {.smaller}

::: {.nonincremental}

Para ter **presença** nessa aula teórica ANP, demostrando que você estudou o conteúdo, você deve fazer a atividade abaixo.

::: {.callout-important title="Entregas no Campus Virtual"}
Responda às duas tarefas no Campus Virtual enviando os seus projetos `contatos-hashmap` e `suporte-tecnico1` com as alterações dos exercícios solicitados ao longo dos slides.
:::

:::
