<!DOCTYPE html>
<html lang="pt-BR"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-59898bd1c6b9d2bb783127feaa000c76.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/quarto-contrib/jquery-3.6.3/jquery-3.6.3.min.js"></script>
<script src="site_libs/quarto-contrib/code-fullscreen-1.0.0/code-fullscreen.js" defer="true"></script>
<link href="site_libs/quarto-contrib/code-fullscreen-1.0.0/code-fullscreen.css" rel="stylesheet">
<script src="site_libs/quarto-contrib/roughnotation-0.5.1/rough-notation.iife.js"></script>
<script src="site_libs/quarto-contrib/roughnotation-init-1.0.0/rough.js"></script><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.33">

  <meta name="author" content="Prof.&nbsp;Julio César Alves">
  <title>GAC125 - Introdução à Programação Orientada a Objetos – IPOO - Cap. 5 Comportamento Mais Sofisticado</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-5858f4e81da34f86931d7ba7687d5e8e.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-pointer/pointer.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">IPOO - Cap. 5 Comportamento Mais Sofisticado</h1>
  <p class="subtitle">Aula 5.1 - Teórica</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
<a href="https://julio.dac.ufla.br">Prof.&nbsp;Julio César Alves</a> 
</div>
        <p class="quarto-title-affiliation">
            DAC - ICET - Universidade Federal de Lavras
          </p>
    </div>
</div>

  <p class="date">26/09/2026</p>
</section>
<section id="section" class="slide level2">
<h2></h2>
<p>Os tópicos abaixo te lembram alguma coisa? :)</p>
<ul>
<li class="fragment"><strong>Praticar enquanto estuda</strong>.</li>
<li class="fragment"><strong>Ler o capítulo do livro</strong>.</li>
<li class="fragment"><strong>Anotar conceitos e dúvidas</strong>.</li>
</ul>
<div class="fragment">
<img data-src="imagens/livro_bluej.png" class="r-stretch">
</div>
</section>
<section id="section-1" class="slide level2">
<h2></h2>
</section>
<section id="principais-conceitos-do-capítulo" class="slide level2">
<h2>Principais Conceitos do Capítulo</h2>
<ul>
<li>Encapsulamento</li>
<li>Atributos e métodos estáticos</li>
<li>Constantes</li>
<li>Uso de classes de biblioteca</li>
<li>Documentação de classes</li>
</ul>
<div class="fragment">
<p>Construções Java do capítulo</p>
<ul>
<li><code>String</code>, <code>Random</code>, <code>static</code>, <code>final</code>, autoboxing, classes empacotadoras.</li>
</ul>
</div>
</section>
<section id="section-2" class="slide level2">
<h2></h2>
<p><img data-src="imagens/aviso_importante.png"></p>
<div class="fragment">
<p>O conceito de <strong>encapsulamento</strong> é fundamental na Programação Orientada a Objetos.</p>
<ul>
<li class="fragment">E será apresentado no final do capítulo.</li>
<li class="fragment">Não deixe de estudar esse conteúdo!!!</li>
</ul>
</div>
</section>
<section id="section-3" class="slide level2">
<h2></h2>
<p>No capítulo anterior conhecemos a classe <code>ArrayList</code> da biblioteca de classes do Java.</p>
<ul>
<li class="fragment">Com ela, ficou mais fácil fazer programas para guardar uma quantidade qualquer de objetos.</li>
<li class="fragment">O que sem ela seria bem mais complicado.</li>
</ul>
<div class="fragment">
<p>Mas ela é apenas um exemplo de classe da biblioteca.</p>
<ul>
<li class="fragment">Existem muitas que serão muito úteis em nossos softwares.</li>
<li class="fragment">E outras que, possivelmente, nunca usaremos.</li>
</ul>
</div>
</section>
<section id="section-4" class="slide level2">
<h2></h2>
<p>Um <strong>bom programador</strong> Java precisa <strong>conseguir trabalhar com as classes da biblioteca</strong>.</p>
<ul>
<li class="fragment">E saber quando utilizar cada uma.</li>
<li class="fragment">De forma a tornar a implementação de um programa mais fácil.</li>
</ul>
<div class="fragment">
<p>Muitas classes da biblioteca têm certas características comuns entre si.</p>
<ul>
<li class="fragment">Especialmente as coleções, são classes que compartilham muitos atributos.</li>
<li class="fragment">E, usando a abstração, podemos tratar de classes de coleções de uma maneira mais geral.</li>
</ul>
</div>
</section>
<section id="section-5" class="slide level2">
<h2></h2>
<p>Neste capítulo, vamos trabalhar com um <strong>sistema de Suporte Técnico</strong>.</p>
<ul>
<li class="fragment">Começaremos com uma versão rudimentar.</li>
<li class="fragment">E ele será melhorado, incrementalmente, utilizando diferentes classes da biblioteca Java.</li>
</ul>
</section>
<section>
<section id="documentação-das-classes-de-biblioteca" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Documentação das classes de biblioteca</h1>

</section>
<section id="section-6" class="slide level2">
<h2></h2>
<p>A biblioteca de classes do Java tem centenas de classes, com muitas opções de métodos.</p>
<ul>
<li class="fragment">Será que um bom programador precisa conhecer todas elas de cor?</li>
</ul>
<div class="fragment">
<p>Na verdade, um bom programador deveria:</p>
<ul>
<li class="fragment">Conhecer <strong>pelo nome as classes mais importantes e seus métodos</strong> (<code>ArrayList</code> é uma delas).</li>
<li class="fragment">Saber <strong>como encontrar informações das demais classes</strong> (tais como métodos e parâmetros).</li>
</ul>
</div>
</section>
<section id="section-7" class="slide level2">
<h2></h2>
<p>O livro da disciplina recomenda que um programador conheça a <strong>documentação do Java</strong> para essas classes.</p>
<ul>
<li class="fragment">A documentação é formada por páginas HTML bem detalhadas sobre todas as classes da biblioteca.</li>
<li class="fragment">Mas para quem não é fluente em inglês, isso pode gerar uma barreira inicial.
<ul>
<li class="fragment">Portanto, uma sugestão é usar também outras fontes para saber como usar as classes,</li>
<li class="fragment">como buscas no Google ou ferramentas de IA, como ChatGPT ou Gemini.</li>
</ul></li>
</ul>
</section>
<section id="section-8" class="slide level2">
<h2></h2>
<p>De toda forma, à medida que você fique mais experiente, saber usar a documentação pode ser muito útil.</p>
<ul>
<li class="fragment">Essa é uma das coisas que separam o programador juninho do bom programador.</li>
</ul>
</section>
<section id="section-9" class="slide level2">
<h2></h2>
<p>Um ponto importante sobre o uso da classe <code>ArrayList</code> é que nós já a utilizamos sem nunca termos visto o código da classe.</p>
<ul>
<li class="fragment">Nós não conferimos como ela foi implementada.</li>
<li class="fragment">E isso não foi necessário para utilizarmos suas funcionalidades.</li>
</ul>
<div class="fragment">
<p>Tudo o que precisamos saber é:</p>
<ul>
<li class="fragment">O nome da classe.</li>
<li class="fragment">As assinaturas dos seus métodos (nomes, parâmetros e tipos de retorno).</li>
<li class="fragment">E o que exatamente esses métodos fazem.</li>
</ul>
</div>
</section>
<section id="section-10" class="slide level2">
<h2></h2>
<p>A mesma coisa acontece em projetos de software grandes de uma empresa.</p>
<ul>
<li class="fragment">Geralmente, várias pessoas trabalham em diferentes partes do sistema.</li>
<li class="fragment">Cada programador deveria se concentrar em sua parte, sem ter que entender detalhes das outras partes.
<ul>
<li class="fragment">Como discutimos ao falar sobre <em>abstração</em> e <em>modularização</em>.</li>
</ul></li>
</ul>
</section>
<section id="section-11" class="slide level2">
<h2></h2>
<p>Cada programador deveria conseguir usar as classes das outras equipes como se elas fossem classes de biblioteca.</p>
<ul>
<li class="fragment">Sabendo o que elas fazem, mas sem precisar saber como elas funcionam internamente.</li>
</ul>
<div class="fragment">
<p>Mas, para isso funcionar, cada membro de equipe deveria documentar sua classe assim como é feito para as classes da biblioteca</p>
<ul>
<li class="fragment">Permitindo que outros programadores usem a classe sem precisar ler o código.</li>
<li class="fragment">Veremos como fazer isso mais adiante neste capítulo.</li>
</ul>
</div>
</section></section>
<section>
<section id="o-sistema-de-suporte-técnico" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>O sistema de suporte técnico</h1>

</section>
<section id="section-12" class="slide level2">
<h2></h2>
<p>A ideia do <strong>sistema de Suporte Técnico</strong> é que ele seja um <strong>chat de atendimento</strong> aos clientes.</p>
<ul>
<li class="fragment">de uma empresa fictícia, chamada <em>DesonestosSistemas</em>.</li>
</ul>
<div class="fragment">
<p>Antigamente a empresa tinha funcionários que faziam atendimento por telefone.</p>
<ul>
<li class="fragment">Mas ela passou por problemas financeiros e demitiu a equipe.
<ul>
<li class="fragment">E não tem dinheiro para criar um chatbot de verdade.</li>
</ul></li>
<li class="fragment">E agora ela quer criar um sistema de suporte para dar a impressão que ela atende os clientes.</li>
<li class="fragment">A ideia é que o sistema imite o atendimento que uma pessoa faria ao telefone.</li>
</ul>
</div>
</section>
<section id="section-13" class="slide level2">
<h2></h2>
<p>Vamos começar com uma versão bem rudimentar do sistema, disponível no projeto <a href="https://github.com/ufla-ipoo/suporte-tecnico1">suporte-tecnico1</a>.</p>
<ul>
<li class="fragment">A ideia é que, ao longo da aula, possamos melhorar o sistema.</li>
<li class="fragment">E, ao longo do processo, vamos aprender diversos conceitos.</li>
</ul>
</section>
<section id="section-14" class="slide level2">
<h2></h2>
<div title="Exercício 1">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 1</strong></p>
</div>
<div class="callout-content">
<p>Experimente a versão rudimentar do sistema de suporte técnico.</p>
<p>Crie um objeto da classe <code>SistemaDeSuporte</code> e chame o método <code>iniciar</code>. Experimente conversar com o sistema pelo terminal e repare como é atendido.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 2">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 2</strong></p>
</div>
<div class="callout-content">
<p>Para conhecermos melhor o projeto, crie um objeto da classe <code>LeitorDeEntrada</code> e experimente seu(s) método(s).</p>
<p>Faça o mesmo com um objeto da classe <code>Respondedor</code>.</p>
</div>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 3">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 3</strong></p>
</div>
<div class="callout-content">
<p>Agora leia o código da classe <code>SistemaDeSuporte</code> e tente entender como ela funciona.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="section-15" class="slide level2">
<h2></h2>
<p>Você deve ter notado que o sistema é realmente muito rudimentar.</p>
<ul>
<li class="fragment">A classe <code>LeitorDeEntrada</code> basicamente retorna uma string digitada pelo usuário no terminal.</li>
<li class="fragment">A classe <code>Respondedor</code> tem um método que sempre retorna a mesma resposta.</li>
<li class="fragment">Já a classe <code>SistemaDeSuporte</code> tem um objeto de cada uma das duas classes anteriores.
<ul>
<li class="fragment">E um loop <code>while</code> que, repetidamente, obtém um texto do usuário e exibe uma resposta.</li>
<li class="fragment">Isso é repetido até que o usuário digite qualquer string que comece com <code>tchau</code>.</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="lendo-documentação-de-classes" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Lendo documentação de classes</h1>

</section>
<section id="section-16" class="slide level2">
<h2></h2>
<p>Experimente usar o sistema de suporte técnico e digitar <code>"Tchau"</code> ou <code>" tchau"</code> (com espaço) para sair.</p>
<ul>
<li class="fragment">O que acontece?</li>
<li class="fragment">Para o usuário isso é muito chato, certo?
<ul>
<li class="fragment">Mas nós podemos usar a documentação da classe String para melhorar isso.</li>
</ul></li>
</ul>
</section>
<section id="section-17" class="slide level2">
<h2></h2>
<p>A classe String é uma das classes da biblioteca padrão do Java.</p>
<ul>
<li class="fragment">Nós podemos acessar a documentação da classe, no BlueJ, no menu <code>Ajuda</code> → <code>Biblioteca de classes de Java</code>.</li>
<li class="fragment">Será aberta a documentação online do Java no seu navegador web.
<ul>
<li class="fragment">Na parte superior direita há uma caixa de busca.</li>
<li class="fragment">Digite <code>string</code> e escolha primeira opção (<code>java.lang.String</code>).</li>
</ul></li>
</ul>
</section>
<section id="section-18" class="slide level2">
<h2></h2>
<div title="Exercício 4">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 4</strong></p>
</div>
<div class="callout-content">
<p>Abra a documentação de alguma outra classe do Java e compare a estrutura da documentação das duas classes. O que as páginas têm em comum?</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 5">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 5</strong></p>
</div>
<div class="callout-content">
<p>Procure pelo método <code>startsWith</code> na documentação da classe <code>String</code>. Veja que o método é sobrecarregado, há duas versões.</p>
<p>Escreva com suas palavras o que as duas versões fazem e a diferença entre eles.</p>
</div>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 6">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 6</strong></p>
</div>
<div class="callout-content">
<p>Há algum método na classe String que retorna quantos caracteres ela tem? Como o método se chama e quais são seus parâmetros?</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="section-19" class="slide level2">
<h2></h2>
<div title="Exercício 7">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 7</strong></p>
</div>
<div class="callout-content">
<p>Procure se existe algum método na classe String que verifica se uma string termina com um dado sufixo. Se existir, como o método se chama, e quais são seus parâmetros e tipo de retorno?</p>
</div>
</div>
</div>
</div>
</section>
<section id="interface-vs.-implementação" class="slide level2" data-auto-animate="True">
<h2 data-id="quarto-animate-title">Interface vs.&nbsp;Implementação</h2>
<p>Você deve ter notado que a documentação tem diferentes tipos de informação:</p>
<ul>
<li class="fragment">o nome da classe;</li>
<li class="fragment">uma descrição geral do objetivo da classe;</li>
<li class="fragment">uma lista dos construtores e métodos da classe;</li>
<li class="fragment">os parâmetros e tipos de retorno de cada construtor e cada método;</li>
<li class="fragment">e uma descrição do objetivo de cada construtor e método.</li>
</ul>
<div class="fragment">
<p>Todas essas informações formam o que chamamos de <span class="alert">interface de uma classe</span>.</p>
</div>
</section>
<section id="interface-vs.-implementação-1" class="slide level2" data-auto-animate="True">
<h2 data-id="quarto-animate-title">Interface vs.&nbsp;Implementação</h2>
<p>Todas essas informações formam o que chamamos de <span class="alert">interface de uma classe</span>.</p>
<ul>
<li class="fragment">Repare que que <strong>a interface não mostra o código</strong> que implementa a classe.</li>
<li class="fragment">Se uma classe é bem descrita (ou seja, sua interface é bem escrita),
<ul>
<li class="fragment">um programador não precisa ver o código da classe para conseguir utilizá-la.</li>
</ul></li>
<li class="fragment">A interface já tem toda a informação que ele precisa.
<ul>
<li class="fragment">(olha a <strong>abstração</strong> aí de novo!)</li>
</ul></li>
</ul>
</section>
<section id="interface-vs.-implementação-2" class="slide level2">
<h2>Interface vs.&nbsp;Implementação</h2>
<p><strong>O código</strong> que não vemos, que é o que faz a classe funcionar, é chamado de <span class="alert">implementação da classe</span>.</p>
<ul>
<li class="fragment">Geralmente um programador trabalha na implementação de uma classe de cada vez,
<ul>
<li class="fragment">e, para isso, usa várias outras classes através de suas interfaces.</li>
</ul></li>
</ul>
<div class="fragment">
<p>Essa diferenciação entre <strong>interface</strong> e <strong>implementação</strong> é um conceito muito importante.</p>
<ul>
<li class="fragment">E vamos ver isso repetidamente nessa disciplina (e em disciplinas avançadas de POO).</li>
</ul>
</div>
</section>
<section id="section-20" class="slide level2">
<h2></h2>
<div title="Nota">
<div class="callout callout-note no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>A palavra <strong>interface</strong> tem diferentes significados em POO. Pode se referir a parte pública visível de uma classe (que é o que acabamos de aprender). Mas pode também se referir a interface gráfica de usuário ou a um tipo especial de classe que você conhecerá se puxar a disciplina Práticas de POO como eletiva. :)</p>
</div>
</div>
</div>
</div>
</section>
<section id="section-21" class="slide level2">
<h2></h2>
<p>Nós também podemos falar de interface de um método específico.</p>
<ul>
<li class="fragment">Veja, por exemplo, a documentação do método <code>length</code> da classe <code>String</code>.</li>
</ul>
<div class="fragment">
<p><img data-src="imagens/java-doc-String-length.png"></p>
</div>
</section>
<section id="section-22" class="slide level2">
<h2></h2>
<img data-src="imagens/java-doc-String-length.png" class="r-stretch">
<p>A interface de um método consiste em sua <strong>assinatura e um comentário</strong>.</p>
<div class="fragment">
<p>E a assinatura de um método contém:</p>
<ul>
<li class="fragment">Um modificador de acesso (<code>public</code>, nesse caso).</li>
<li class="fragment">O tipo de retorno do método (<code>int</code>, nesse caso).</li>
<li class="fragment">O nome do método.</li>
<li class="fragment">Uma lista de parâmetros (vazia, nesse caso).</li>
</ul>
</div>
</section>
<section id="section-23" class="slide level2">
<h2></h2>
<p><img data-src="imagens/java-doc-String-length.png"></p>
<p>Repare que a interface do método tem tudo que precisamos saber para conseguirmos usá-lo.</p>
</section>
<section id="section-24" class="slide level2">
<h2></h2>
<div title="Conceito">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Conceito</strong></p>
</div>
<div class="callout-content">
<p>A <strong>interface</strong> de uma classe descreve o que a classe faz e como ela pode ser usada sem mostrar a implementação.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Conceito">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Conceito</strong></p>
</div>
<div class="callout-content">
<p>O código-fonte completo que define uma classe é chamado de <strong>implementação</strong> da classe.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="usando-métodos-de-classes-da-biblioteca" class="slide level2">
<h2>Usando métodos de classes da biblioteca</h2>
<p>Em nosso sistema de suporte, já vimos que o sistema não aceita que o usuário digite <code>"Tchau"</code> ou <code>" tchau"</code>.</p>
<ul>
<li class="fragment">Vamos melhorar isso de forma que todas essas variações sejam reconhecidas como <code>"tchau"</code>.</li>
</ul>
<div class="fragment">
<div title="Exercício 8">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 8</strong></p>
</div>
<div class="callout-content">
<p>Encontre o método <code>trim</code> na documentação da classe <code>String</code>. Escreva com suas palavras o que ele faz, e como ele poderia ser chamado usando uma variável <code>String</code> chamada <code>texto</code>.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="section-25" class="slide level2">
<h2></h2>
<p>Um importante detalhe sobre objetos String em Java, é que eles são <strong>imutáveis</strong>.</p>
<ul>
<li class="fragment">Isso significa que esses objetos não podem ser alterados depois de criados.</li>
<li class="fragment">Repare que o método <code>trim</code>, por exemplo, retorna uma nova String.
<ul>
<li class="fragment">Ele não modifica a String original.</li>
</ul></li>
</ul>
</section>
<section id="section-26" class="slide level2">
<h2></h2>
<div class="columns">
<div class="column" style="width:30%;">
<p><img data-src="imagens/fica_a_dica.png"></p>
</div><div class="column" style="width:70%;">
<p>É um erro comum em Java, tentar alterar uma String usando chamadas como:</p>
<p><code>texto.toUpperCase();</code></p>
</div></div>
<div class="fragment">
<p>Essa chamada não provoca nenhum erro, mas também não causa nenhum efeito. Isso porque o método retorna uma nova String; ele não altera a original.</p>
<ul>
<li class="fragment"><p>Portanto, se queremos alterar a variável <code>texto</code>, precisamos descartar o objeto String original, atribuindo à variável <code>texto</code> a nova String gerada:</p>
<p><code>texto = texto.toUpperCase();</code></p></li>
</ul>
</div>
</section>
<section id="section-27" class="slide level2">
<h2></h2>
<p>Pelo que você leu sobre o método <code>trim</code> na documentação, como podemos usá-lo no sistema de suporte?</p>
<ul>
<li class="fragment">Você deve ter visto que podemos usá-lo para remover espaços no início e no final da string.</li>
</ul>
</section>
<section id="section-28" class="slide level2">
<h2></h2>
<p>O código da classe <code>SistemaDeSuporte</code> poderia ser então alterado da seguinte forma:</p>
<div class="halfincfontsize">
<div class="sourceCode" id="cb1"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a>    <span class="bu">String</span> entrada <span class="op">=</span> leitor<span class="op">.</span><span class="fu">obterEntrada</span><span class="op">();</span></span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a>    entrada <span class="op">=</span> entrada<span class="op">.</span><span class="fu">trim</span><span class="op">();</span></span>
<span id="cb1-3"><a aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span><span class="op">(</span>entrada<span class="op">.</span><span class="fu">startsWith</span><span class="op">(</span><span class="st">"tchau"</span><span class="op">))</span> <span class="op">{</span></span>
<span id="cb1-4"><a aria-hidden="true" tabindex="-1"></a>        terminou <span class="op">=</span> <span class="kw">true</span><span class="op">;</span></span>
<span id="cb1-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span>
<span id="cb1-6"><a aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span> <span class="op">{</span></span>
<span id="cb1-7"><a aria-hidden="true" tabindex="-1"></a>        <span class="bu">String</span> resposta <span class="op">=</span> respondedor<span class="op">.</span><span class="fu">generateResponse</span><span class="op">();</span></span>
<span id="cb1-8"><a aria-hidden="true" tabindex="-1"></a>        <span class="bu">System</span><span class="op">.</span><span class="fu">out</span><span class="op">.</span><span class="fu">println</span><span class="op">(</span>resposta<span class="op">);</span></span>
<span id="cb1-9"><a aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section-29" class="slide level2">
<h2></h2>
<p>Qual a diferença entre escrever essas duas linhas de código:</p>
<div class="halfincfontsize">
<div class="sourceCode" id="cb2"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb2-1"><a aria-hidden="true" tabindex="-1"></a>    <span class="bu">String</span> entrada <span class="op">=</span> leitor<span class="op">.</span><span class="fu">obterEntrada</span><span class="op">();</span></span>
<span id="cb2-2"><a aria-hidden="true" tabindex="-1"></a>    entrada <span class="op">=</span> entrada<span class="op">.</span><span class="fu">trim</span><span class="op">();</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>ou escrever esse código?</p>
<div class="halfincfontsize">
<div class="sourceCode" id="cb3"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a>    <span class="bu">String</span> entrada <span class="op">=</span> leitor<span class="op">.</span><span class="fu">obterEntrada</span><span class="op">().</span><span class="fu">trim</span><span class="op">();</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<p>O efeito é exatamente o mesmo.</p>
<ul>
<li class="fragment">Você pode escolher a forma que acha mais fácil de entender.</li>
<li class="fragment">Veja que na segunda opção, a ordem de execução é como se existissem os parênteses como mostrado abaixo.</li>
</ul>
</div>
<div class="fragment">
<div class="halfincfontsize">
<div class="sourceCode" id="cb4"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb4-1"><a aria-hidden="true" tabindex="-1"></a>  <span class="bu">String</span> entrada <span class="op">=</span> <span class="op">(</span>leitor<span class="op">.</span><span class="fu">obterEntrada</span><span class="op">()).</span><span class="fu">trim</span><span class="op">();</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="section-30" class="slide level2">
<h2></h2>
<div title="Conceito">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Conceito</strong></p>
</div>
<div class="callout-content">
<p>Um objeto é chamado <strong>imutável</strong> se seu conteúdo ou estado não pode ser alterado depois que ele foi criado. Strings são exemplos de objetos imutáveis.</p>
</div>
</div>
</div>
</div>
</section>
<section id="section-31" class="slide level2">
<h2></h2>
<div title="Exercício 9">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 9</strong></p>
</div>
<div class="callout-content">
<p>Implemente a alteração na classe <code>SistemaDeSuporte</code> usando o método <code>trim</code> da classe String. Teste a alteração digitando espaço antes da palavra tchau.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 10">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 10</strong></p>
</div>
<div class="callout-content">
<p>O exercício anterior ainda não resolveu o problema do usuário digitar <code>"Tchau"</code> com letra maiúscula.</p>
<p>Veja na documentação da classe String como funciona o método <code>toLowerCase</code> e o utilize de forma que o programa saia independente do usuário digitar tchau com letras maiúsculas ou minúsculas.</p>
</div>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 11">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 11</strong></p>
</div>
<div class="callout-content">
<p>Encontre o método <code>equals</code> na documentação da classe String. Utilize o método <code>equals</code> em vez do método <code>startsWith</code> na implementação da classe <code>SuporteTecnico</code></p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="section-32" class="slide level2">
<h2></h2>
<div class="columns">
<div class="column" style="width:30%;">
<p><img data-src="imagens/fica_a_dica.png"></p>
</div><div class="column" style="width:70%;">
<p>Lembre-se que, como já foi dito em aulas práticas anteriores, não podemos comparar objetos String em Java utilizando o operador <code>==</code>.</p>
<ul>
<li>Usando o operador estamos verificando se é o mesmo objeto, e não se os dois objetos têm o mesmo conteúdo.</li>
<li>Para comparar se dois objetos String têm o mesmo conteúdo, devemos utilizar o método <code>equals</code>.</li>
</ul>
</div></div>
</section></section>
<section>
<section id="adicionando-comportamento-aleatório" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Adicionando comportamento aleatório</h1>

</section>
<section id="section-33" class="slide level2">
<h2></h2>
<p>No início da disciplina, nós utilizamos um objeto da classe <code>Random</code> no exercício da Nave para acrescentar aleatoriedade em nosso jogo.</p>
<ul>
<li class="fragment">Nós podemos agora utilizar a mesma classe para mudar o comportamento do <code>Respondedor</code> do nosso sistema de suporte.</li>
<li class="fragment">A ideia é que o sistema exiba respostas aleatórias, em vez de sempre responder a mesma coisa.</li>
</ul>
</section>
<section id="section-34" class="slide level2">
<h2></h2>
<p>Nós podemos fazer isso, alterando a classe <code>Respondedor</code> seguindo os passos abaixo:</p>
<ul>
<li class="fragment">declarando um atributo do tipo <code>Random</code> para guardar um gerador de números aleatórios;</li>
<li class="fragment">declarando um atributo do tipo <code>ArrayList</code> para guardar nossas possíveis respostas;</li>
<li class="fragment">criando os objetos <code>Random</code> e <code>ArrayList</code> no construtor da classe <code>Respondedor</code>;</li>
<li class="fragment">preenchendo a lista com algumas frases de resposta;</li>
<li class="fragment">selecionando e retornando uma frase aleatória quando o método <code>gerarResposta</code> é chamado.</li>
</ul>
</section>
<section id="section-35" class="slide level2">
<h2></h2>
<div title="Exercício 12">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 12</strong></p>
</div>
<div class="callout-content">
<p>Melhore a classe <code>Respondedor</code> de forma que ela gere respostas aleatórias como descrito no slide anterior.</p>
<p>Veja que, para gerar respostas aleatórias, basta sortearmos uma posição do <code>ArrayList</code> e usarmos essa posição para obter uma mensagem. Podemos sortear uma posição usando o método <code>nextInt</code> da classe <code>Random</code>, e o método <code>size</code> da classe <code>ArrayList</code>.</p>
<p><strong>Dicas</strong>:</p>
<ul>
<li>Veja no próximo slide alguns exemplos de frase de resposta (mas não precisam ser exatamente essas, use sua criatividade!).</li>
<li>Reveja o exercício da Nave para se lembrar como usar a classe <code>Random</code>.</li>
<li>Leia a seção 5.4 do livro da disciplina.</li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section id="section-36" class="slide level2">
<h2></h2>
<p>Exemplos de frases de resposta do sistema de suporte técnico:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb5-1"><a aria-hidden="true" tabindex="-1"></a><span class="st">"Isso parece estranho. Você poderia descrever com mais detalhes?"</span></span>
<span id="cb5-2"><a aria-hidden="true" tabindex="-1"></a><span class="st">"Nenhum outro cliente reclamou disso antes. Qual é a configuração do seu sistema?"</span></span>
<span id="cb5-3"><a aria-hidden="true" tabindex="-1"></a><span class="st">"Poderia me dar mais informações sobre o problema?"</span></span>
<span id="cb5-4"><a aria-hidden="true" tabindex="-1"></a><span class="st">"Isso é abordado no manual. Você já leu o manual?"</span></span>
<span id="cb5-5"><a aria-hidden="true" tabindex="-1"></a><span class="st">"Sua descrição não é clara. Você tem um especialista com você que poderia descrever isso melhor?"</span></span>
<span id="cb5-6"><a aria-hidden="true" tabindex="-1"></a><span class="st">"Isso não é um bug, é uma funcionalidade!"</span></span>
<span id="cb5-7"><a aria-hidden="true" tabindex="-1"></a><span class="st">"Você poderia detalhar melhor isso?"</span></span>
<span id="cb5-8"><a aria-hidden="true" tabindex="-1"></a><span class="st">"Você já tentou executar o aplicativo no seu telefone?"</span></span>
<span id="cb5-9"><a aria-hidden="true" tabindex="-1"></a><span class="st">"Já verifiquei no Google e ChatGPT e nem eles sabem como responder :("</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section></section>
<section>
<section id="pacotes-e-import" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Pacotes e <code>import</code></h1>

</section>
<section id="section-37" class="slide level2">
<h2></h2>
<p>No exercício anterior usamos as linhas de código abaixo:</p>
<div class="halfincfontsize">
<div class="sourceCode" id="cb6"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb6-1"><a aria-hidden="true" tabindex="-1"></a><span class="kw">import</span> <span class="im">java</span><span class="op">.</span><span class="im">util</span><span class="op">.</span><span class="im">ArrayList</span><span class="op">;</span></span>
<span id="cb6-2"><a aria-hidden="true" tabindex="-1"></a><span class="kw">import</span> <span class="im">java</span><span class="op">.</span><span class="im">util</span><span class="op">.</span><span class="im">Random</span><span class="op">;</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<p>Nós já usamos <code>import</code> antes, mas vamos agora entender um pouco mais sobre ele.</p>
</div>
</section>
<section id="section-38" class="slide level2">
<h2></h2>
<p>As classes da biblioteca de classes do Java não ficam disponíveis automaticamente, como as outras classes do projeto.</p>
<ul>
<li class="fragment">Para usá-las precisamos informar isso para o compilador.</li>
<li class="fragment">Esse processo é chamado de <span class="alert">importação</span> de classe.
<ul>
<li class="fragment">E é feito usando a palavra-chave <code>import</code>.</li>
</ul></li>
</ul>
<div class="fragment">
<p>O comando <code>import</code> tem o seguinte formato:</p>
<div class="halfincfontsize">
<div class="sourceCode" id="cb7"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb7-1"><a aria-hidden="true" tabindex="-1"></a><span class="kw">import</span> <span class="im">nome_qualificado_da_classe</span><span class="op">;</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="section-39" class="slide level2">
<h2></h2>
<p>Como a biblioteca de classes do Java possui milhares de classes,</p>
<ul>
<li class="fragment">é necessário ter alguma forma de organização que facilite a utilização delas.</li>
</ul>
<div class="fragment">
<p>Java usa <span class="alert">pacotes</span> para organizar as classes em grupos.</p>
<ul>
<li class="fragment">E os pacotes podem ser aninhados (ou seja, os pacotes podem conter outros pacotes).</li>
</ul>
</div>
</section>
<section id="section-40" class="slide level2">
<h2></h2>
<p>As classes <code>ArrayList</code> e <code>Random</code>, por exemplo, fazem parte do pacote <code>java.util</code>.</p>
<ul>
<li class="fragment">Nós podemos ver essa informação na documentação das classes.</li>
</ul>
<div class="fragment">
<p>O <strong>nome completo</strong> ou <span class="alert">nome qualificado</span> de uma classe é:</p>
<ul>
<li class="fragment">o nome do seu pacote, seguido de um ponto, seguido do nome da classe.</li>
<li class="fragment">Assim, o nome completo da classe <code>ArrayList</code>, por exemplo, é: <code>java.util.ArrayList</code>.</li>
</ul>
</div>
</section>
<section id="section-41" class="slide level2">
<h2></h2>
<p>Java também nos permite importar pacotes completos com o comando:</p>
<div class="halfincfontsize">
<div class="sourceCode" id="cb8"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb8-1"><a aria-hidden="true" tabindex="-1"></a><span class="kw">import</span> <span class="im">nome_do_pacote</span><span class="op">.*;</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<p>Portanto, o comando abaixo importaria todas as classes do pacote <code>java.util</code>:</p>
<div class="halfincfontsize">
<div class="sourceCode" id="cb9"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb9-1"><a aria-hidden="true" tabindex="-1"></a><span class="kw">import</span> <span class="im">java</span><span class="op">.</span><span class="im">util</span><span class="op">.*;</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="fragment">
<p>Mas, apesar da linguagem permitir isso, é uma boa prática importar apenas as classes que você realmente vai usar.</p>
<ul>
<li class="fragment">A vantagem é a legibilidade, pois fica claro quais classes são realmente necessárias.</li>
</ul>
</div>
</section>
<section id="section-42" class="slide level2">
<h2></h2>
<p>Há uma exceção a essas regras de pacotes:</p>
<ul>
<li class="fragment">Algumas classes são tão usadas que seriam importadas em quase todas as classes que implementamos.</li>
<li class="fragment">Essas classes pertecem ao pacote <code>java.lang</code>.</li>
</ul>
<div class="fragment">
<p>Esse pacote é importado automaticamente pelo compilador em todas as classes.</p>
<ul>
<li class="fragment">Portanto, não precisamos usar o comando <code>import</code> para esse pacote.</li>
<li class="fragment">A classe <code>String</code> é um exemplo de classe desse pacote.</li>
</ul>
</div>
</section></section>
<section>
<section id="usando-mapas-para-associações" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Usando mapas para associações</h1>

</section>
<section id="section-43" class="slide level2">
<h2></h2>
<p>Nosso sistema ficou mais dinâmico, mas ainda não é nada convincente,</p>
<ul>
<li class="fragment">pois as respostas são independentes do que o usuário escreve.</li>
</ul>
<div class="fragment">
<p>Nós podemos melhorar um pouco isso, tentando responder algo pelo menos próximo do que o usuário perguntou.</p>
<ul>
<li class="fragment">A ideia é identificar alguma palavra-chave na pergunta feita pelo usuário.</li>
<li class="fragment">e fornecer uma resposta que tenha algo a ver com essa palavra-chave.</li>
</ul>
</div>
</section>
<section id="section-44" class="slide level2">
<h2></h2>
<p>Por exemplo, suponha que na pergunta do usuário apareça a palavra <code>"lento"</code>.</p>
<ul>
<li class="fragment">A resposta poderia ser então algo como:</li>
</ul>
<div class="fragment">
<blockquote>
<p>Acredito que isso tem a ver com o seu hardware. Atualizar seu processador deve resolver todos os problemas de desempenho. Você tem algum problema com nosso software?</p>
</blockquote>
</div>
</section>
<section id="section-45" class="slide level2">
<h2></h2>
<p>Já se na pergunta do usuário aparecer a palava <code>"bug"</code>, a resposta poderia ser:</p>
<div class="fragment">
<blockquote>
<p>Bem, você sabe, todo software tem alguns bugs. Mas nossos engenheiros de software estão trabalhando muito para corrigi-los. Você pode descrever o problema com mais detalhes?</p>
</blockquote>
</div>
</section>
<section id="section-46" class="slide level2">
<h2></h2>
<p>Mas como podemos implementar isso?</p>
<ul>
<li class="fragment">Basicamente, nós precisamos <strong>associar</strong> uma resposta a uma palvra-chave.</li>
</ul>
<div class="fragment">
<p>Poderíamos tratar isso com uma sequência de <code>if-else if</code>.</p>
<ul>
<li class="fragment">Mas, aproveitaremos a oportunidade para conhecer um novo tipo de coleção: <strong>mapas</strong>.</li>
</ul>
</div>
</section>
<section id="section-47" class="slide level2">
<h2></h2>
<p>Um <span class="alert">Mapa</span> é uma <strong>coleção de pares de objetos chave-valor</strong>.</p>
<ul>
<li class="fragment">Assim como um <code>ArrayList</code>, um Mapa pode guardar uma quantidade flexível de entradas.</li>
<li class="fragment">Mas uma diferença importante é que em um Mapa, <strong>uma entrada</strong> não é um objeto, e sim <strong>um par de objetos</strong>.
<ul>
<li class="fragment">Este par é formado por um objeto <strong>chave</strong> e um objeto <strong>valor</strong>.</li>
</ul></li>
</ul>
<div class="fragment">
<p>Enquanto com <code>ArrayList</code> buscamos objetos pela sua posição,</p>
<ul>
<li class="fragment">com um Mapa, usamos o objeto chave para buscar o objeto valor associado a ele.</li>
</ul>
</div>
</section>
<section id="section-48" class="slide level2">
<h2></h2>
<p>Você consegue pensar em um exemplo de Mapa, ou seja, de coleção de dados organizados na forma de pares chave/valor?</p>
<ul>
<li class="fragment">Um exemplo bem comum de um Mapa é a lista de contatos de um celular.</li>
<li class="fragment">A lista de contatos tem entradas, e cada entrada é um par: um nome e um número de telefone.</li>
</ul>
<div class="fragment">
<p>Usamos a lista de contatos procurando por um nome e, ao encontrá-lo, obtemos o número de telefone associado a ele.</p>
<ul>
<li class="fragment">Nós não procuramos os contatos por um índice ou posição.</li>
<li class="fragment">Portanto, nós <strong>buscamos um valor</strong> (o número de telefone), <strong>a partir de uma chave</strong> (o nome).</li>
</ul>
</div>
</section>
<section id="section-49" class="slide level2">
<h2></h2>
<p>Na lista de contatos de um celular poderíamos ter uma coleção como a seguinte:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Nome</th>
<th>Número</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tião</td>
<td>(35) 9999 1111</td>
</tr>
<tr class="even">
<td>Maria</td>
<td>(35) 8888 1234</td>
</tr>
<tr class="odd">
<td>Joaquim</td>
<td>(31) 9876 5432</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Neste exemplo, a primeira entrada tem a chave <code>"Tião"</code> e o valor <code>"(35) 9999 1111"</code>.</p>
<ul>
<li class="fragment">Poderíamos buscar um número a partir da chave <code>"Maria"</code>.
<ul>
<li class="fragment">E a resposta a esta busca seria <code>"(35) 8888 1234"</code>.</li>
</ul></li>
</ul>
</div>
</section>
<section id="section-50" class="slide level2">
<h2></h2>
<p>Você consegue pensar em outros exemplos de coleções na forma de Mapa que usamos no dia a dia?</p>
<div class="fragment">
<p>Um <strong>dicionário</strong>:</p>
<ul>
<li class="fragment">Buscamos um significado (valor) a partir de uma palavra (chave).</li>
</ul>
</div>
<div class="fragment">
<p><strong>Siglas e nomes de estados</strong>:</p>
<ul>
<li class="fragment">Podemos buscar o nome de um estado (valor) a partir de sua sigla (chave).</li>
</ul>
</div>
</section>
<section id="section-51" class="slide level2">
<h2></h2>
<p><strong>Uma coleção de alunos</strong>:</p>
<ul>
<li class="fragment">Podemos buscar um objeto aluno (valor) a partir da sua matrícula (chave).</li>
</ul>
<div class="fragment">
<div title="Conceito">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Conceito</strong></p>
</div>
<div class="callout-content">
<p>Um <strong>mapa</strong> é uma coleção que guarda pares chave/valor como entradas. Valores podem ser buscados forncendo-se a chave correspondente.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="section-52" class="slide level2">
<h2></h2>
<img data-src="imagens/balao_como_usar_estrutura_mapa.png" class="r-stretch">
<div class="fragment">
<p>A forma mais simples de usar essa estrutura é através da classe <code>HashMap</code>.</p>
<ul>
<li class="fragment"><code>HashMap</code> é uma implementação particular de Mapa.</li>
</ul>
</div>
</section>
<section id="section-53" class="slide level2">
<h2></h2>
<p>Os métodos mais importantes da classe <code>HashMap</code> são: <code>put</code> e <code>get</code>.</p>
<ul>
<li class="fragment">O método <code>put</code> insere uma entrada no mapa (um par de objetos chave/valor).</li>
<li class="fragment">Já o método <code>get</code> recupera o valor associado a uma chave.</li>
</ul>
</section>
<section id="section-54" class="slide level2">
<h2></h2>
<p>O trecho de código abaixo cria um <code>HashMap</code> e insere nele três entradas.</p>
<ul>
<li class="fragment">Cada entrada é um par chave/valor consistindo de um nome e um número de telefone.</li>
</ul>
<div class="halfincfontsize">
<div class="sourceCode" id="cb10"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb10-1"><a aria-hidden="true" tabindex="-1"></a>    <span class="bu">HashMap</span><span class="op">&lt;</span><span class="bu">String</span><span class="op">,</span><span class="bu">String</span><span class="op">&gt;</span> contatos <span class="op">=</span> <span class="kw">new</span> <span class="bu">HashMap</span><span class="op">&lt;&gt;();</span></span>
<span id="cb10-2"><a aria-hidden="true" tabindex="-1"></a>    contatos<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"Tiao"</span><span class="op">,</span> <span class="st">"(35) 9999 1111"</span><span class="op">);</span></span>
<span id="cb10-3"><a aria-hidden="true" tabindex="-1"></a>    contatos<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"Maria"</span><span class="op">,</span> <span class="st">"(35) 8888 1234"</span><span class="op">);</span></span>
<span id="cb10-4"><a aria-hidden="true" tabindex="-1"></a>    contatos<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"Joaquim"</span><span class="op">,</span> <span class="st">"(31) 9876 5432"</span><span class="op">);</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section-55" class="slide level2">
<h2></h2>
<p>Quando declaramos uma variável do tipo <code>HashMap</code>, e quando criamos um objeto <code>HashMap</code>,</p>
<ul>
<li class="fragment">precisamos informar os tipos dos objetos que serão guardados.</li>
<li class="fragment">Assim como fazemos com <code>ArrayList</code>.</li>
</ul>
<div class="fragment">
<p>No caso do <code>HashMap</code>, precisamos informar <strong>dois tipos</strong>:</p>
<ul>
<li class="fragment">o tipo dos objetos chave e o tipo dos objetos valor.</li>
</ul>
</div>
</section>
<section id="section-56" class="slide level2">
<h2></h2>
<p>No caso da lista de contatos, por exemplo, definimos que tanto a chave quanto o valor são objetos do tipo <code>String</code>.</p>
<div class="halfincfontsize">
<div class="sourceCode" id="cb11"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb11-1"><a aria-hidden="true" tabindex="-1"></a>    <span class="bu">HashMap</span><span class="op">&lt;</span><span class="bu">String</span><span class="op">,</span><span class="bu">String</span><span class="op">&gt;</span> contatos <span class="op">=</span> <span class="kw">new</span> <span class="bu">HashMap</span><span class="op">&lt;&gt;();</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<p>O trecho de código abaixo encontra e exibe o telefone da Maria.</p>
<div class="halfincfontsize">
<div class="sourceCode" id="cb12"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb12-1"><a aria-hidden="true" tabindex="-1"></a>    <span class="bu">String</span> telefone <span class="op">=</span> contatos<span class="op">.</span><span class="fu">get</span><span class="op">(</span><span class="st">"Maria"</span><span class="op">);</span></span>
<span id="cb12-2"><a aria-hidden="true" tabindex="-1"></a>    <span class="bu">System</span><span class="op">.</span><span class="fu">out</span><span class="op">.</span><span class="fu">println</span><span class="op">(</span><span class="st">"Telefone da Maria: "</span> <span class="op">+</span> telefone<span class="op">);</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="fragment">
<p>Repare que passamos a chave (o nome <code>"Maria"</code>) para o método <code>get</code> e ele nos retorna o valor (o número do telefone dela).</p>
</div>
</section>
<section id="section-57" class="slide level2">
<h2></h2>
<div title="Exercício 13">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 13</strong></p>
</div>
<div class="callout-content">
<p>Faça uma busca na internet sobre a documentação dos métodos <code>get</code> e <code>put</code> da classe <code>HashMap</code> e veja se a explicação bate com o que você está entendendo até o momento.</p>
</div>
</div>
</div>
</div>
</section>
<section id="section-58" class="slide level2">
<h2></h2>
<div title="Exercício 14">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 14</strong></p>
</div>
<div class="callout-content">
<p>Crie no BlueJ um projeto chamado <code>contatos-hashmap</code>.</p>
<p>Crie uma classe chamada <code>Contatos</code> e use um <code>HashMap</code> para implementar uma lista de contatos similar à que vimos anteriormente. Lembre-se que você deve importar <code>java.util.HashMap</code>.</p>
<p>Na classe, implemente dois métodos:</p>
<div class="halfincfontsize">
<div class="sourceCode" id="cb13"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb13-1"><a aria-hidden="true" tabindex="-1"></a>    <span class="kw">public</span> <span class="dt">void</span> <span class="fu">cadastrarNumero</span><span class="op">(</span><span class="bu">String</span> nome<span class="op">,</span> <span class="bu">String</span> numero<span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>e</p>
<div class="halfincfontsize">
<div class="sourceCode" id="cb14"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb14-1"><a aria-hidden="true" tabindex="-1"></a>    <span class="kw">public</span> <span class="bu">String</span> <span class="fu">buscarNumero</span><span class="op">(</span><span class="bu">String</span> nome<span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Esses novos métodos devem usar os métodos <code>put</code> e <code>get</code> da classe <code>HashMap</code> para implementar suas funcionalidades.</p>
</div>
</div>
</div>
</div>
</section>
<section id="section-59" class="slide level2">
<h2></h2>
<div title="Exercício 15">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 15</strong></p>
</div>
<div class="callout-content">
<p>Experimente com o BlueJ o que acontece quando você adiciona uma entrada em uma mapa com uma chave que já existia no mapa.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 16">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 16</strong></p>
</div>
<div class="callout-content">
<p>Experimente com o BlueJ o que acontece quando você adiciona duas entradas em um mapa com o mesmo valor, mas com chaves diferentes.</p>
</div>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 17">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 17</strong></p>
</div>
<div class="callout-content">
<p>Experimente com o BlueJ o que acontece quando você tenta procurar um valor e a chave fornecida não existe no mapa.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="section-60" class="slide level2">
<h2></h2>
<p>Para os exercícios a seguir, você pode usar a <a href="https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/HashMap.html">documentação</a> oficial da classe <code>HashMap</code> do Java.</p>
<ul>
<li class="fragment">Ou pode usar uma ferramenta de IA para obter as respostas.</li>
<li class="fragment">De todo modo, quanto mais familiarizado estiver com a documentação oficial, melhor.</li>
</ul>
</section>
<section id="section-61" class="slide level2">
<h2></h2>
<div title="Exercício 18">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 18</strong></p>
</div>
<div class="callout-content">
<p>Descubra como podemos saber quantas entradas estão guardadas em um <code>HashMap</code>.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 19">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 19</strong></p>
</div>
<div class="callout-content">
<p>Como você pode verificar se uma chave existe em um mapa? Escreva um código Java de exemplo.</p>
</div>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 20">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 20</strong></p>
</div>
<div class="callout-content">
<p>Como podemos imprimir todas as chaves que estão armazenadas em um <code>HashMap</code>.</p>
<ul>
<li>Atenção, não vale aqui construções de programação funcional (que usam o operador <code>-&gt;</code>, por exemplo).</li>
</ul>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="usando-um-mapa-no-sistema-de-suporte" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Usando um mapa no sistema de suporte</h1>

</section>
<section id="section-62" class="slide level2">
<h2></h2>
<p>Agora que conhecemos o conceito de Mapa, podemos fazer a melhoria que conversamos antes:</p>
<ul>
<li class="fragment">dar uma resposta para o usuário que tenha alguma relação com sua dúvida.</li>
</ul>
<div class="fragment">
<p>Podemos fazer a implementação usando um <code>HashMap</code>.</p>
<ul>
<li class="fragment">A ideia é ter um mapa que relacione palavras como <code>"lento"</code> e <code>"bug"</code> com as respostas correspondentes a estas palavras.</li>
<li class="fragment">Portanto, o mapa terá como chave uma <code>String</code> e como valor também uma <code>String</code>.</li>
</ul>
</div>
</section>
<section id="section-63" class="slide level2">
<h2></h2>
<p>Vamos começar, criando uma atributo na classe <code>Respondedor</code>, chamado <code>mapaDeRespostas</code>.</p>
<ul>
<li class="fragment">E, no construtor, vamos criar o <code>HashMap</code> e chamar um novo método <code>preencherMapaDeRespostas</code>, para colocar no objeto todas as respostas que tivermos.</li>
</ul>
<div class="fragment">
<div class="halfincfontsize">
<div class="sourceCode" id="cb15"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb15-1"><a aria-hidden="true" tabindex="-1"></a>  <span class="kw">private</span> <span class="bu">HashMap</span><span class="op">&lt;</span><span class="bu">String</span><span class="op">,</span> <span class="bu">String</span><span class="op">&gt;</span> mapaDeRespostas<span class="op">;</span></span>
<span id="cb15-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="kw">public</span> Respondedor <span class="op">{</span></span>
<span id="cb15-4"><a aria-hidden="true" tabindex="-1"></a>    mapaDeRespostas <span class="op">=</span> <span class="kw">new</span> <span class="bu">HashMap</span><span class="op">&lt;&gt;();</span></span>
<span id="cb15-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="fu">preencherMapaDeRespostas</span><span class="op">();</span></span>
<span id="cb15-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="op">}</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="section-64" class="slide level2">
<h2></h2>
<p>Vamos então implementar o método <code>preencherMapaDeRespostas</code> acrescentando todas as repostas que nosso sistema será capaz de fornecer.</p>
<div class="fragment">
<div class="sourceCode" id="cb16"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb16-1"><a aria-hidden="true" tabindex="-1"></a>  <span class="kw">private</span> <span class="dt">void</span> <span class="fu">preencherMapaDeRespostas</span><span class="op">()</span> <span class="op">{</span></span>
<span id="cb16-2"><a aria-hidden="true" tabindex="-1"></a>    mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"lento"</span><span class="op">,</span> </span>
<span id="cb16-3"><a aria-hidden="true" tabindex="-1"></a>      <span class="st">"Acredito que isso tem a ver com o seu hardware. "</span> <span class="op">+</span></span>
<span id="cb16-4"><a aria-hidden="true" tabindex="-1"></a>      <span class="st">"Atualizar seu processador deve resolver todos os problemas de desempenho. "</span> <span class="op">+</span></span>
<span id="cb16-5"><a aria-hidden="true" tabindex="-1"></a>      <span class="st">"Você tem algum problema com nosso software?"</span><span class="op">);</span></span>
<span id="cb16-6"><a aria-hidden="true" tabindex="-1"></a>    mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"bug"</span><span class="op">,</span></span>
<span id="cb16-7"><a aria-hidden="true" tabindex="-1"></a>      <span class="st">"Bem, você sabe, todo software tem alguns bugs. "</span> <span class="op">+</span></span>
<span id="cb16-8"><a aria-hidden="true" tabindex="-1"></a>      <span class="st">"Mas nossos engenheiros de software estão trabalhando muito para corrigi-los. "</span> <span class="op">+</span></span>
<span id="cb16-9"><a aria-hidden="true" tabindex="-1"></a>      <span class="st">"Você pode descrever o problema com mais detalhes?"</span><span class="op">);</span></span>
<span id="cb16-10"><a aria-hidden="true" tabindex="-1"></a>    <span class="co">// continue preenchendo as demais respostas possíveis</span></span>
<span id="cb16-11"><a aria-hidden="true" tabindex="-1"></a>  <span class="op">}</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li class="fragment">Repare que o método é privado, pois foi criado para ser acessado apenas dentro da própria classe <code>Respondedor</code>.</li>
</ul>
</div>
</section>
<section id="section-65" class="slide level2">
<h2></h2>
<p>Aqui está um exemplo de implementação mais completa.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb17-1"><a aria-hidden="true" tabindex="-1"></a><span class="kw">private</span> <span class="dt">void</span> <span class="fu">preencherMapaDeRespostas</span><span class="op">()</span> <span class="op">{</span></span>
<span id="cb17-2"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"lento"</span><span class="op">,</span> </span>
<span id="cb17-3"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"Acredito que isso tem a ver com o seu hardware. Atualizar seu processador deve resolver todos os problemas de desempenho. Você tem algum problema com nosso software?"</span><span class="op">);</span></span>
<span id="cb17-4"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"bug"</span><span class="op">,</span></span>
<span id="cb17-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"Bem, você sabe, todo software tem alguns bugs. Mas nossos engenheiros de software estão trabalhando muito para corrigi-los. Você pode descrever o problema com mais detalhes?"</span><span class="op">);</span></span>
<span id="cb17-6"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"travou"</span><span class="op">,</span></span>
<span id="cb17-7"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"Bem, nunca trava em nosso sistema. Deve ter algo a ver com o seu sistema. Conte mais sobre sua configuração."</span><span class="op">);</span></span>
<span id="cb17-8"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"travando"</span><span class="op">,</span></span>
<span id="cb17-9"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"Bem, nunca trava em nosso sistema. Deve ter algo a ver com o seu sistema. Conte mais sobre sua configuração."</span><span class="op">);</span></span>
<span id="cb17-10"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"lento"</span><span class="op">,</span></span>
<span id="cb17-11"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"Acredito que isso tem a ver com o seu hardware. Atualizar seu processador deve resolver todos os problemas de desempenho. Você tem algum problema com nosso software?"</span><span class="op">);</span></span>
<span id="cb17-12"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"desempenho"</span><span class="op">,</span></span>
<span id="cb17-13"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"O desempenho foi bastante adequado em todos os nossos testes. Você está executando outros processos em segundo plano?"</span><span class="op">);</span></span>
<span id="cb17-14"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"bug"</span><span class="op">,</span></span>
<span id="cb17-15"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"Bem, você sabe, todo software tem alguns bugs. Mas nossos engenheiros de software estão trabalhando muito para corrigi-los. Você pode descrever o problema com mais detalhes?"</span><span class="op">);</span></span>
<span id="cb17-16"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"erro"</span><span class="op">,</span></span>
<span id="cb17-17"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"Bem, você sabe, todo software tem alguns bugs. Mas nossos engenheiros de software estão trabalhando muito para corrigi-los. Você pode descrever o problema com mais detalhes?"</span><span class="op">);</span></span>
<span id="cb17-18"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"windows"</span><span class="op">,</span></span>
<span id="cb17-19"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"Este é um bug conhecido relacionado ao sistema operacional Windows. Por favor, informe à Microsoft. Não há nada que possamos fazer a respeito."</span><span class="op">);</span></span>
<span id="cb17-20"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"mac"</span><span class="op">,</span></span>
<span id="cb17-21"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"Este é um bug conhecido relacionado ao sistema operacional Mac. Por favor, informe à Apple. Não há nada que possamos fazer a respeito."</span><span class="op">);</span></span>
<span id="cb17-22"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"caro"</span><span class="op">,</span></span>
<span id="cb17-23"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"O custo de nosso produto é bastante competitivo. Você deu uma olhada e realmente comparou nossos recursos?"</span><span class="op">);</span></span>
<span id="cb17-24"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"instalação"</span><span class="op">,</span></span>
<span id="cb17-25"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"A instalação é realmente bastante simples. Temos muitos assistentes que fazem todo o trabalho para você. Você leu as instruções de instalação?"</span><span class="op">);</span></span>
<span id="cb17-26"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"memória"</span><span class="op">,</span></span>
<span id="cb17-27"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"Se você ler atentamente os requisitos do sistema, verá que os requisitos de memória especificados são de 6 gigabytes. Você realmente deve atualizar sua memória. Mais alguma coisa que você gostaria de saber?"</span><span class="op">);</span></span>
<span id="cb17-28"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"linux"</span><span class="op">,</span></span>
<span id="cb17-29"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"Levamos o suporte ao Linux muito a sério. Mas há alguns problemas. A maioria está relacionada a versões incompatíveis do glibc. Você pode ser um pouco mais preciso?"</span><span class="op">);</span></span>
<span id="cb17-30"><a aria-hidden="true" tabindex="-1"></a>  mapaDeRespostas<span class="op">.</span><span class="fu">put</span><span class="op">(</span><span class="st">"bluej"</span><span class="op">,</span></span>
<span id="cb17-31"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"Ah, o BlueJ, sim. Tentamos comprá-los há muito tempo, mas eles simplesmente não vendem... São pessoas teimosas. Não há nada que possamos fazer a respeito, desculpe."</span><span class="op">);</span></span>
<span id="cb17-32"><a aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="section-66" class="slide level2">
<h2></h2>
<p>Abaixo temos uma primeira tentativa de alteração do método <code>gerarResposta</code> para usar as respostas que criamos.</p>
<ul>
<li class="fragment">Vamos começar simplificando as coisas:
<ul>
<li class="fragment">assumindo que o usuário digitará uma única palavra.</li>
</ul></li>
</ul>
<div class="fragment">
<div class="sourceCode" id="cb18"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb18-1"><a aria-hidden="true" tabindex="-1"></a>  <span class="kw">public</span> <span class="bu">String</span> <span class="fu">gerarResposta</span><span class="op">(</span><span class="bu">String</span> palavra<span class="op">)</span></span>
<span id="cb18-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="op">{</span></span>
<span id="cb18-3"><a aria-hidden="true" tabindex="-1"></a>    <span class="bu">String</span> resposta <span class="op">=</span> mapaDeRespostas<span class="op">.</span><span class="fu">get</span><span class="op">(</span>palavra<span class="op">);</span></span>
<span id="cb18-4"><a aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="op">(</span>resposta <span class="op">!=</span> <span class="kw">null</span><span class="op">)</span> <span class="op">{</span></span>
<span id="cb18-5"><a aria-hidden="true" tabindex="-1"></a>      <span class="cf">return</span> resposta<span class="op">;</span></span>
<span id="cb18-6"><a aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span>
<span id="cb18-7"><a aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span> <span class="op">{</span></span>
<span id="cb18-8"><a aria-hidden="true" tabindex="-1"></a>      <span class="co">// Se chegamos aqui, é porque a palavra não foi reconhecida.</span></span>
<span id="cb18-9"><a aria-hidden="true" tabindex="-1"></a>      <span class="co">// Neste caso, pegamos uma de nossas respostas aleatórias</span></span>
<span id="cb18-10"><a aria-hidden="true" tabindex="-1"></a>      <span class="co">// que tínhamos criado antes.</span></span>
<span id="cb18-11"><a aria-hidden="true" tabindex="-1"></a>      <span class="cf">return</span> <span class="fu">pegarRespostaPadrao</span><span class="op">();</span></span>
<span id="cb18-12"><a aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span>
<span id="cb18-13"><a aria-hidden="true" tabindex="-1"></a>  <span class="op">}</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section-67" class="slide level2">
<h2></h2>
<div title="Exercício 21">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 21</strong></p>
</div>
<div class="callout-content">
<p>Aplique as últimas alterações ao projeto de suporte técnico.</p>
<p>Você precisará alterar também a chamada ao método <code>gerarResposta</code> feita na classe <code>SistemaDeSuporte</code>.</p>
</div>
</div>
</div>
</div>
</section>
<section id="section-68" class="slide level2">
<h2></h2>
<p>O sistema está respodendo bem melhor agora,</p>
<ul>
<li class="fragment">mas desde que o usuário digite apenas uma palavra, em vez de uma pergunta completa.</li>
</ul>
<div class="fragment">
<p>O ideal é deixarmos o usuário digitar uma pergunta inteira,</p>
<ul>
<li class="fragment">e tentar reconhecer nela alguma das palavras tratadas.</li>
</ul>
</div>
<div class="fragment">
<p>Para isso, precisaremos alterar a classe <code>LeitorDeEntrada</code> para que ela retorne a entrada como um conjunto de palavras</p>
<ul>
<li class="fragment">em vez de retornar uma única String.</li>
<li class="fragment">É o que veremos a seguir.</li>
</ul>
</div>
</section></section>
<section>
<section id="usando-conjuntos" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Usando conjuntos</h1>

</section>
<section id="section-69" class="slide level2">
<h2></h2>
<p>A biblioteca de classes do Java possui diferentes tipos de <a href=".alert">conjuntos</a> implementados em diferentes classes.</p>
<ul>
<li class="fragment">Uma delas é chamada <code>HashSet</code>.</li>
</ul>
<div class="fragment">
<div title="Exercício 22">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 22</strong></p>
</div>
<div class="callout-content">
<p>Busque na documentação do Java, ou usando uma ferramenta de IA, quais são as similaridades e as diferenças entre um <code>HashSet</code> e um <code>ArrayList</code>.</p>
<p>Para os curiosos: tente entender porque <code>ArrayList</code> é um caso especial de <code>List</code> e <code>HashSet</code> é um caso especial de <code>Set</code>.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="section-70" class="slide level2">
<h2></h2>
<p>A declaração de um <code>HashSet</code>,</p>
<ul>
<li class="fragment">a criação do objeto</li>
<li class="fragment">e a adição de elementos é feita da mesma forma que um <code>ArrayList</code>.</li>
</ul>
<div class="fragment">
<div class="halfincfontsize">
<div class="sourceCode" id="cb19"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb19-1"><a aria-hidden="true" tabindex="-1"></a>    <span class="kw">import</span> <span class="im">java</span><span class="op">.</span><span class="im">util</span><span class="op">.</span><span class="im">HashSet</span><span class="op">;</span></span>
<span id="cb19-2"><a aria-hidden="true" tabindex="-1"></a>    <span class="op">.</span> <span class="op">.</span> <span class="op">.</span></span>
<span id="cb19-3"><a aria-hidden="true" tabindex="-1"></a>    <span class="fu">HashSet</span><span class="op">&lt;</span><span class="bu">String</span><span class="op">&gt;</span> conjunto <span class="op">=</span> <span class="kw">new</span> <span class="bu">HashSet</span><span class="op">&lt;&gt;();</span></span>
<span id="cb19-4"><a aria-hidden="true" tabindex="-1"></a>    conjunto<span class="op">.</span><span class="fu">add</span><span class="op">(</span><span class="st">"um"</span><span class="op">);</span></span>
<span id="cb19-5"><a aria-hidden="true" tabindex="-1"></a>    conjunto<span class="op">.</span><span class="fu">add</span><span class="op">(</span><span class="st">"dois"</span><span class="op">);</span></span>
<span id="cb19-6"><a aria-hidden="true" tabindex="-1"></a>    conjunto<span class="op">.</span><span class="fu">add</span><span class="op">(</span><span class="st">"três"</span><span class="op">);</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="section-71" class="slide level2">
<h2></h2>
<p>Para percorrer um <code>HashSet</code> podemos usar um <code>for-each</code>,</p>
<ul>
<li class="fragment">igualzinho ao que usamos para <code>ArrayList</code>.</li>
</ul>
<div class="halfincfontsize">
<div class="sourceCode" id="cb20"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb20-1"><a aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span><span class="op">(</span><span class="bu">String</span> elemento <span class="op">:</span> conjunto<span class="op">)</span> <span class="op">{</span></span>
<span id="cb20-2"><a aria-hidden="true" tabindex="-1"></a>        <span class="co">// faz alguma coisa com o elemento.</span></span>
<span id="cb20-3"><a aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<p>Repare, portanto, que <strong>usar diferentes coleções</strong> em Java <strong>é</strong> sempre <strong>muito parecido</strong>.</p>
<ul>
<li class="fragment">Se você entender como usar uma delas, você conseguirá usar as outras com facilidade.</li>
</ul>
</div>
</section>
<section id="section-72" class="slide level2">
<h2></h2>
<p>As <strong>diferenças</strong> entre as coleções <strong>estão nos</strong> seus <strong>comportamentos</strong>.</p>
<ul>
<li class="fragment">Uma lista, por exemplo, mantém a ordem dos elementos, permite acesso aos elementos por posição, e permite elementos repetidos.</li>
<li class="fragment">Já um conjunto não mantém a ordem dos elementos, e garante que não existem elementos repetidos.
<ul>
<li class="fragment">Portanto, os elementos podem ser percorridos no <code>for-each</code> em ordem diferente da que eles foram inseridos.</li>
<li class="fragment">E inserir um mesmo elemento uma segunda vez, simplesmente não tem nenhum efeito.</li>
</ul></li>
</ul>
</section>
<section id="dividindo-strings" class="slide level2">
<h2>Dividindo Strings</h2>
<p>Agora que sabemos como usar um <code>set</code>,</p>
<ul>
<li class="fragment">vamos verificar como podemos pegar a entrada do usuário,</li>
<li class="fragment">quebrá-la,</li>
<li class="fragment">e guardar as palavras em um conjunto de string.</li>
</ul>
<div class="fragment">
<p>Vamos fazer isso alterando o método <code>obterEntrada</code> da classe <code>LeitorDeEntrada</code>.</p>
</div>
</section>
<section id="section-73" class="slide level2">
<h2></h2>
<div class="sourceCode" id="cb21"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb21-1"><a aria-hidden="true" tabindex="-1"></a>  <span class="kw">public</span> <span class="bu">HashSet</span><span class="op">&lt;</span><span class="bu">String</span><span class="op">&gt;</span> <span class="fu">obterEntrada</span><span class="op">()</span></span>
<span id="cb21-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="op">{</span></span>
<span id="cb21-3"><a aria-hidden="true" tabindex="-1"></a>    <span class="bu">System</span><span class="op">.</span><span class="fu">out</span><span class="op">.</span><span class="fu">print</span><span class="op">(</span><span class="st">"&gt; "</span><span class="op">);</span>         <span class="co">// imprime o prompt</span></span>
<span id="cb21-4"><a aria-hidden="true" tabindex="-1"></a>    <span class="bu">String</span> linhaDeEntrada <span class="op">=</span> leitor<span class="op">.</span><span class="fu">nextLine</span><span class="op">().</span><span class="fu">trim</span><span class="op">().</span><span class="fu">toLowerCase</span><span class="op">();</span></span>
<span id="cb21-5"><a aria-hidden="true" tabindex="-1"></a>                                    <span class="co">// quebra nos espaços</span></span>
<span id="cb21-6"><a aria-hidden="true" tabindex="-1"></a>    <span class="bu">String</span><span class="op">[]</span> vetorDePalavras <span class="op">=</span> linhaDeEntrada<span class="op">.</span><span class="fu">split</span><span class="op">(</span><span class="st">" "</span><span class="op">);</span> </span>
<span id="cb21-7"><a aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb21-8"><a aria-hidden="true" tabindex="-1"></a>    <span class="co">// adiciona palavras de um vetor em um HashSet</span></span>
<span id="cb21-9"><a aria-hidden="true" tabindex="-1"></a>    <span class="bu">HashSet</span><span class="op">&lt;</span><span class="bu">String</span><span class="op">&gt;</span> palavras <span class="op">=</span> <span class="kw">new</span> <span class="bu">HashSet</span><span class="op">&lt;&gt;();</span></span>
<span id="cb21-10"><a aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span><span class="op">(</span><span class="bu">String</span> palavra <span class="op">:</span> vetorDePalavras<span class="op">)</span> <span class="op">{</span></span>
<span id="cb21-11"><a aria-hidden="true" tabindex="-1"></a>      palavras<span class="op">.</span><span class="fu">add</span><span class="op">(</span>palavra<span class="op">);</span></span>
<span id="cb21-12"><a aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span>
<span id="cb21-13"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-14"><a aria-hidden="true" tabindex="-1"></a>      <span class="cf">return</span> palavras<span class="op">;</span></span>
<span id="cb21-15"><a aria-hidden="true" tabindex="-1"></a>  <span class="op">}</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li class="fragment">Estamos usando os métodos <code>trim</code> e <code>toLowerCase</code> que vimos anteriormente.</li>
<li class="fragment">O método <code>split</code> usa o parâmetro passado para dividir uma string e um vetor de substrings.</li>
</ul>
</section>
<section id="section-74" class="slide level2">
<h2></h2>
<div title="Exercício 23">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 23</strong></p>
</div>
<div class="callout-content">
<p>O método <code>split</code> é mais poderoso do que pode parecer pelo nosso exemplo. Como você pode definir exatamente como uma string deve ser quebrada? Dê alguns exemplos.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 24">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 24</strong></p>
</div>
<div class="callout-content">
<p>Escreva como seria possível quebrar uma string armazenada em uma variável <code>linha</code> contendo palavras separadas por ponto-e-vírgula.</p>
</div>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 25">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 25</strong></p>
</div>
<div class="callout-content">
<p>Qual seria a diferença no resultado retornado pelo método <code>obterEntrada</code>, se o retorno fosse um <code>ArrayList</code> em vez de um <code>HashSet</code>?</p>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="finalizando-o-sistema-de-suporte" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Finalizando o Sistema de Suporte</h1>

</section>
<section id="section-75" class="slide level2">
<h2></h2>
<p>Precisamos agora alterar as classes <code>SistemaDeSuporte</code> e <code>Respondedor</code></p>
<ul>
<li class="fragment">para que lidem com um conjunto de palavras em vez de uma única string.</li>
</ul>
</section>
<section id="section-76" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title"></h2>
<p>Vamos começar alterando o método <code>iniciar</code> da classe <code>SistemaDeSuporte</code>.</p>
<div class="sourceCode" id="annotated-cell-6"><pre class="sourceCode java code-annotation-code code-with-copy" data-id="quarto-animate-code"><code class="sourceCode java hljs"><span id="annotated-cell-6-1" class="hljs-ln-code"><a href="#annotated-cell-6-1" aria-hidden="true" tabindex="-1"></a>  <span class="kw">public</span> <span class="dt">void</span> <span class="fu">iniciar</span><span class="op">()</span></span>
<span id="annotated-cell-6-2" class="hljs-ln-code"><a href="#annotated-cell-6-2" aria-hidden="true" tabindex="-1"></a>  <span class="op">{</span></span>
<span id="annotated-cell-6-3" class="hljs-ln-code"><a href="#annotated-cell-6-3" aria-hidden="true" tabindex="-1"></a>    <span class="dt">boolean</span> terminou <span class="op">=</span> <span class="kw">false</span><span class="op">;</span></span>
<span id="annotated-cell-6-4" class="hljs-ln-code"><a href="#annotated-cell-6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-6-5" class="hljs-ln-code"><a href="#annotated-cell-6-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">imprimirBoasVindas</span><span class="op">();</span></span>
<span id="annotated-cell-6-6" class="hljs-ln-code"><a href="#annotated-cell-6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-6-7" class="hljs-ln-code"><a href="#annotated-cell-6-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">while</span><span class="op">(!</span>terminou<span class="op">)</span> <span class="op">{</span></span>
<span id="annotated-cell-6-8" class="hljs-ln-code"><a href="#annotated-cell-6-8" aria-hidden="true" tabindex="-1"></a>      <span class="bu">HashSet</span><span class="op">&lt;</span><span class="bu">String</span><span class="op">&gt;</span> entrada <span class="op">=</span> leitor<span class="op">.</span><span class="fu">obterEntrada</span><span class="op">();</span></span>
<span id="annotated-cell-6-9" class="hljs-ln-code"><a href="#annotated-cell-6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-6-10" class="hljs-ln-code"><a href="#annotated-cell-6-10" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span><span class="op">(</span>entrada<span class="op">.</span><span class="fu">contains</span><span class="op">(</span><span class="st">"tchau"</span><span class="op">))</span> <span class="op">{</span></span>
<span id="annotated-cell-6-11" class="hljs-ln-code"><a href="#annotated-cell-6-11" aria-hidden="true" tabindex="-1"></a>        terminou <span class="op">=</span> <span class="kw">true</span><span class="op">;</span></span>
<span id="annotated-cell-6-12" class="hljs-ln-code"><a href="#annotated-cell-6-12" aria-hidden="true" tabindex="-1"></a>      <span class="op">}</span></span>
<span id="annotated-cell-6-13" class="hljs-ln-code"><a href="#annotated-cell-6-13" aria-hidden="true" tabindex="-1"></a>      <span class="cf">else</span> <span class="op">{</span></span>
<span id="annotated-cell-6-14" class="hljs-ln-code"><a href="#annotated-cell-6-14" aria-hidden="true" tabindex="-1"></a>        <span class="bu">String</span> resposta <span class="op">=</span> respondedor<span class="op">.</span><span class="fu">gerarResposta</span><span class="op">(</span>entrada<span class="op">);</span></span>
<span id="annotated-cell-6-15" class="hljs-ln-code"><a href="#annotated-cell-6-15" aria-hidden="true" tabindex="-1"></a>        <span class="bu">System</span><span class="op">.</span><span class="fu">out</span><span class="op">.</span><span class="fu">println</span><span class="op">(</span>resposta<span class="op">);</span></span>
<span id="annotated-cell-6-16" class="hljs-ln-code"><a href="#annotated-cell-6-16" aria-hidden="true" tabindex="-1"></a>      <span class="op">}</span></span>
<span id="annotated-cell-6-17" class="hljs-ln-code"><a href="#annotated-cell-6-17" aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span>
<span id="annotated-cell-6-18" class="hljs-ln-code"><a href="#annotated-cell-6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-6-19" class="hljs-ln-code"><a href="#annotated-cell-6-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">imprimirDespedida</span><span class="op">();</span></span>
<span id="annotated-cell-6-20" class="hljs-ln-code"><a href="#annotated-cell-6-20" aria-hidden="true" tabindex="-1"></a>  <span class="op">}</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="section-77" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title"></h2>
<div class="sourceCode" id="annotated-cell-7" data-code-line-numbers="8,10"><pre class="sourceCode java code-annotation-code code-with-copy code-annotated" data-id="quarto-animate-code"><code class="sourceCode java hljs"><span id="annotated-cell-7-1" class="hljs-ln-code"><a href="#annotated-cell-7-1" aria-hidden="true" tabindex="-1"></a>  <span class="kw">public</span> <span class="dt">void</span> <span class="fu">iniciar</span><span class="op">()</span></span>
<span id="annotated-cell-7-2" class="hljs-ln-code"><a href="#annotated-cell-7-2" aria-hidden="true" tabindex="-1"></a>  <span class="op">{</span></span>
<span id="annotated-cell-7-3" class="hljs-ln-code"><a href="#annotated-cell-7-3" aria-hidden="true" tabindex="-1"></a>    <span class="dt">boolean</span> terminou <span class="op">=</span> <span class="kw">false</span><span class="op">;</span></span>
<span id="annotated-cell-7-4" class="hljs-ln-code"><a href="#annotated-cell-7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-7-5" class="hljs-ln-code"><a href="#annotated-cell-7-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">imprimirBoasVindas</span><span class="op">();</span></span>
<span id="annotated-cell-7-6" class="hljs-ln-code"><a href="#annotated-cell-7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-7-7" class="hljs-ln-code"><a href="#annotated-cell-7-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">while</span><span class="op">(!</span>terminou<span class="op">)</span> <span class="op">{</span></span>
<a class="code-annotation-anchor hljs-ln-code" data-target-cell="annotated-cell-7" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-7-8" class="code-annotation-target hljs-ln-code"><a href="#annotated-cell-7-8" aria-hidden="true" tabindex="-1"></a>      <span class="bu">HashSet</span><span class="op">&lt;</span><span class="bu">String</span><span class="op">&gt;</span> entrada <span class="op">=</span> leitor<span class="op">.</span><span class="fu">obterEntrada</span><span class="op">();</span></span>
<span id="annotated-cell-7-9" class="hljs-ln-code"><a href="#annotated-cell-7-9" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor hljs-ln-code" data-target-cell="annotated-cell-7" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-7-10" class="code-annotation-target hljs-ln-code"><a href="#annotated-cell-7-10" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span><span class="op">(</span>entrada<span class="op">.</span><span class="fu">contains</span><span class="op">(</span><span class="st">"tchau"</span><span class="op">))</span> <span class="op">{</span></span>
<span id="annotated-cell-7-11" class="hljs-ln-code"><a href="#annotated-cell-7-11" aria-hidden="true" tabindex="-1"></a>        terminou <span class="op">=</span> <span class="kw">true</span><span class="op">;</span></span>
<span id="annotated-cell-7-12" class="hljs-ln-code"><a href="#annotated-cell-7-12" aria-hidden="true" tabindex="-1"></a>      <span class="op">}</span></span>
<span id="annotated-cell-7-13" class="hljs-ln-code"><a href="#annotated-cell-7-13" aria-hidden="true" tabindex="-1"></a>      <span class="cf">else</span> <span class="op">{</span></span>
<span id="annotated-cell-7-14" class="hljs-ln-code"><a href="#annotated-cell-7-14" aria-hidden="true" tabindex="-1"></a>        <span class="bu">String</span> resposta <span class="op">=</span> respondedor<span class="op">.</span><span class="fu">gerarResposta</span><span class="op">(</span>entrada<span class="op">);</span></span>
<span id="annotated-cell-7-15" class="hljs-ln-code"><a href="#annotated-cell-7-15" aria-hidden="true" tabindex="-1"></a>        <span class="bu">System</span><span class="op">.</span><span class="fu">out</span><span class="op">.</span><span class="fu">println</span><span class="op">(</span>resposta<span class="op">);</span></span>
<span id="annotated-cell-7-16" class="hljs-ln-code"><a href="#annotated-cell-7-16" aria-hidden="true" tabindex="-1"></a>      <span class="op">}</span></span>
<span id="annotated-cell-7-17" class="hljs-ln-code"><a href="#annotated-cell-7-17" aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span>
<span id="annotated-cell-7-18" class="hljs-ln-code"><a href="#annotated-cell-7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-7-19" class="hljs-ln-code"><a href="#annotated-cell-7-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">imprimirDespedida</span><span class="op">();</span></span>
<span id="annotated-cell-7-20" class="hljs-ln-code"><a href="#annotated-cell-7-20" aria-hidden="true" tabindex="-1"></a>  <span class="op">}</span></span><div class="code-annotation-gutter-bg hljs-ln-code"></div><div class="code-annotation-gutter hljs-ln-code"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<dl class="code-annotation-container-grid">
<dt class="fragment" data-target-cell="annotated-cell-7" data-target-annotation="1">1</dt>
<dd class="fragment">
<span data-code-cell="annotated-cell-7" data-code-lines="8" data-code-annotation="1">alteramos o tipo da variável <code>entrada</code> para que seja um <code>HashSet</code> (precisamos importar a classe).</span>
</dd>
<dt class="fragment" data-target-cell="annotated-cell-7" data-target-annotation="2">2</dt>
<dd class="fragment">
<span data-code-cell="annotated-cell-7" data-code-lines="10" data-code-annotation="2">mudamos a verificação que finaliza o sistema, passando a usar o método <code>contains</code>.</span>
</dd>
</dl>
</section>
<section id="section-78" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title"></h2>
<p>Por fim, vamos alterar o método <code>gerarResposta</code> da classe <code>Respondedor</code></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode java code-with-copy" data-id="quarto-animate-code"><code class="sourceCode java hljs"><span id="cb22-1" class="hljs-ln-code"><a aria-hidden="true" tabindex="-1"></a>    <span class="kw">public</span> <span class="bu">String</span> <span class="fu">gerarResposta</span><span class="op">(</span><span class="bu">HashSet</span><span class="op">&lt;</span><span class="bu">String</span><span class="op">&gt;</span> palavras<span class="op">)</span></span>
<span id="cb22-2" class="hljs-ln-code"><a aria-hidden="true" tabindex="-1"></a>    <span class="op">{</span></span>
<span id="cb22-3" class="hljs-ln-code"><a aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> <span class="op">(</span><span class="bu">String</span> palavra <span class="op">:</span> palavras<span class="op">)</span> <span class="op">{</span></span>
<span id="cb22-4" class="hljs-ln-code"><a aria-hidden="true" tabindex="-1"></a>            <span class="bu">String</span> resposta <span class="op">=</span> mapaDeRespostas<span class="op">.</span><span class="fu">get</span><span class="op">(</span>palavra<span class="op">);</span></span>
<span id="cb22-5" class="hljs-ln-code"><a aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="op">(</span>resposta <span class="op">!=</span> <span class="kw">null</span><span class="op">)</span> <span class="op">{</span></span>
<span id="cb22-6" class="hljs-ln-code"><a aria-hidden="true" tabindex="-1"></a>                <span class="cf">return</span> resposta<span class="op">;</span></span>
<span id="cb22-7" class="hljs-ln-code"><a aria-hidden="true" tabindex="-1"></a>            <span class="op">}</span></span>
<span id="cb22-8" class="hljs-ln-code"><a aria-hidden="true" tabindex="-1"></a>        <span class="op">}</span></span>
<span id="cb22-9" class="hljs-ln-code"><a aria-hidden="true" tabindex="-1"></a>        <span class="co">// Se chegamos aqui, é porque a palavra não foi reconhecida.</span></span>
<span id="cb22-10" class="hljs-ln-code"><a aria-hidden="true" tabindex="-1"></a>        <span class="co">// Neste caso, pegamos uma de nossas respostas aleatórias</span></span>
<span id="cb22-11" class="hljs-ln-code"><a aria-hidden="true" tabindex="-1"></a>        <span class="co">// que tínhamos criado antes.</span></span>
<span id="cb22-12" class="hljs-ln-code"><a aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="fu">pegarRespostaPadrao</span><span class="op">();</span></span>
<span id="cb22-13" class="hljs-ln-code"><a aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="section-79" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title"></h2>
<div class="sourceCode" id="annotated-cell-9" data-code-line-numbers="1,3-8"><pre class="sourceCode java code-annotation-code code-with-copy code-annotated" data-id="quarto-animate-code"><code class="sourceCode java hljs"><a class="code-annotation-anchor hljs-ln-code" data-target-cell="annotated-cell-9" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-9-1" class="code-annotation-target hljs-ln-code"><a href="#annotated-cell-9-1" aria-hidden="true" tabindex="-1"></a>    <span class="kw">public</span> <span class="bu">String</span> <span class="fu">gerarResposta</span><span class="op">(</span><span class="bu">HashSet</span><span class="op">&lt;</span><span class="bu">String</span><span class="op">&gt;</span> palavras<span class="op">)</span></span>
<span id="annotated-cell-9-2" class="hljs-ln-code"><a href="#annotated-cell-9-2" aria-hidden="true" tabindex="-1"></a>    <span class="op">{</span></span>
<a class="code-annotation-anchor hljs-ln-code" data-target-cell="annotated-cell-9" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-9-3" class="code-annotation-target hljs-ln-code"><a href="#annotated-cell-9-3" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> <span class="op">(</span><span class="bu">String</span> palavra <span class="op">:</span> palavras<span class="op">)</span> <span class="op">{</span></span>
<span id="annotated-cell-9-4" class="hljs-ln-code"><a href="#annotated-cell-9-4" aria-hidden="true" tabindex="-1"></a>            <span class="bu">String</span> resposta <span class="op">=</span> mapaDeRespostas<span class="op">.</span><span class="fu">get</span><span class="op">(</span>palavra<span class="op">);</span></span>
<span id="annotated-cell-9-5" class="hljs-ln-code"><a href="#annotated-cell-9-5" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="op">(</span>resposta <span class="op">!=</span> <span class="kw">null</span><span class="op">)</span> <span class="op">{</span></span>
<span id="annotated-cell-9-6" class="hljs-ln-code"><a href="#annotated-cell-9-6" aria-hidden="true" tabindex="-1"></a>                <span class="cf">return</span> resposta<span class="op">;</span></span>
<span id="annotated-cell-9-7" class="hljs-ln-code"><a href="#annotated-cell-9-7" aria-hidden="true" tabindex="-1"></a>            <span class="op">}</span></span>
<span id="annotated-cell-9-8" class="hljs-ln-code"><a href="#annotated-cell-9-8" aria-hidden="true" tabindex="-1"></a>        <span class="op">}</span></span>
<span id="annotated-cell-9-9" class="hljs-ln-code"><a href="#annotated-cell-9-9" aria-hidden="true" tabindex="-1"></a>        <span class="co">// Se chegamos aqui, é porque a palavra não foi reconhecida.</span></span>
<span id="annotated-cell-9-10" class="hljs-ln-code"><a href="#annotated-cell-9-10" aria-hidden="true" tabindex="-1"></a>        <span class="co">// Neste caso, pegamos uma de nossas respostas aleatórias</span></span>
<span id="annotated-cell-9-11" class="hljs-ln-code"><a href="#annotated-cell-9-11" aria-hidden="true" tabindex="-1"></a>        <span class="co">// que tínhamos criado antes.</span></span>
<span id="annotated-cell-9-12" class="hljs-ln-code"><a href="#annotated-cell-9-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="fu">pegarRespostaPadrao</span><span class="op">();</span></span>
<span id="annotated-cell-9-13" class="hljs-ln-code"><a href="#annotated-cell-9-13" aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span><div class="code-annotation-gutter-bg hljs-ln-code"></div><div class="code-annotation-gutter hljs-ln-code"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<dl class="code-annotation-container-grid">
<dt class="fragment" data-target-cell="annotated-cell-9" data-target-annotation="1">1</dt>
<dd class="fragment">
<span data-code-cell="annotated-cell-9" data-code-lines="1" data-code-annotation="1">O método agora recebe um <code>HashSet</code> em vez de uma <code>String</code>.</span>
</dd>
<dt class="fragment" data-target-cell="annotated-cell-9" data-target-annotation="2">2</dt>
<dd class="fragment">
<span data-code-cell="annotated-cell-9" data-code-lines="3" data-code-annotation="2">Percorremos as palavras do <code>HashSet</code> e a primeira que for uma das palavras que tratamos, nós retornamos a resposta.</span>
</dd>
</dl>
</section>
<section id="para-reforçar-em-casa" class="slide level2">
<h2>Para reforçar (em casa)</h2>
<div title="Exercício 26">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 26</strong></p>
</div>
<div class="callout-content">
<p>Adicione pelo menos mais uma resposta ao sistema de suporte técnico.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 27">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 27</strong></p>
</div>
<div class="callout-content">
<p>Garanta que uma resposta padrão nunca é retornada duas vezes seguidas.</p>
</div>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 28">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 28</strong></p>
</div>
<div class="callout-content">
<p>Altere o código para que, em vez de retornar a resposta para a primeira palavra identicada, o programa identifique todas as palavras presentes na pergunta do usuário e tente responder da forma mais apropriada.</p>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="autoboxing-e-classes-empacotadoras" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Autoboxing e classes empacotadoras</h1>

</section>
<section id="section-80" class="slide level2">
<h2></h2>
<p>Nós vimos que um <code>ArrayList</code> consegue guardar qualquer tipo de objeto.</p>
<ul>
<li class="fragment">Mas como <code>int</code> não é um objeto, não é possível usar um <code>ArrayList</code> para guardar uma lista de números inteiros?</li>
</ul>
<div class="fragment">
<p>Isso é possível através das <span class="alert">classes empacotadoras (<em>wrapper classes</em>)</span>.</p>
<ul>
<li class="fragment">Cada tipo primitivo em Java tem uma <strong>classe empacotadora</strong> que representa o mesmo tipo,
<ul>
<li class="fragment">Mas que é um objeto de verdade.</li>
</ul></li>
<li class="fragment">A classe empacotadora para <code>int</code>, por exemplo, se chama <code>Integer</code>.</li>
</ul>
</div>
</section>
<section id="section-81" class="slide level2">
<h2></h2>
<p>Nós poderíamos criar explicitamente um objeto do tipo <code>Integer</code>:</p>
<div class="halfincfontsize">
<div class="sourceCode" id="cb23"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb23-1"><a aria-hidden="true" tabindex="-1"></a>    <span class="dt">int</span> n <span class="op">=</span> <span class="dv">10</span><span class="op">;</span></span>
<span id="cb23-2"><a aria-hidden="true" tabindex="-1"></a>    <span class="bu">Integer</span> objetoInt <span class="op">=</span> <span class="kw">new</span> <span class="bu">Integer</span><span class="op">(</span>n<span class="op">);</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<p>E poderíamos então declarar um <code>ArrayList&lt;Integer&gt;</code> e guardar nele o <code>objetoInt</code>.</p>
</div>
</section>
<section id="section-82" class="slide level2">
<h2></h2>
<p>Mas, na verdade, nós nunca fazemos isso, pois podemos guardar valores de tipo primitivo no <code>ArrayList</code>!</p>
<ul>
<li class="fragment">Isso porque sempre que um valor de tipo primitivo é usado em um contexto que requer um tipo empacotador (<em>wrapper</em>),</li>
<li class="fragment">o compilador converte o valor automaticamente em um objeto empacotador correspondente.</li>
</ul>
<div class="fragment">
<p>Essa funcionalidade se chama <span class="alert"><em>autoboxing</em></span></p>
<ul>
<li class="fragment">(algo como, auto-empacotamento).</li>
</ul>
</div>
</section>
<section id="section-83" class="slide level2">
<h2></h2>
<p>Portanto, na prática, podemos escrever código como mostrado abaixo:</p>
<div class="halfincfontsize">
<div class="sourceCode" id="cb24"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb24-1"><a aria-hidden="true" tabindex="-1"></a>    <span class="kw">private</span> <span class="bu">ArrayList</span><span class="op">&lt;</span><span class="bu">Integer</span><span class="op">&gt;</span> notas<span class="op">;</span></span>
<span id="cb24-2"><a aria-hidden="true" tabindex="-1"></a>    <span class="kw">...</span></span>
<span id="cb24-3"><a aria-hidden="true" tabindex="-1"></a>    <span class="kw">public</span> <span class="dt">void</span> <span class="fu">guardarNotasNaLista</span><span class="op">(</span><span class="dt">int</span> nota<span class="op">)</span> <span class="op">{</span></span>
<span id="cb24-4"><a aria-hidden="true" tabindex="-1"></a>        notas<span class="op">.</span><span class="fu">add</span><span class="op">(</span>nota<span class="op">);</span></span>
<span id="cb24-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<p>Repare que estamos guardando o valor da variável <code>nota</code>, do tipo <code>int</code>, em um <code>ArrayList&lt;Integer&gt;</code>.</p>
</div>
</section>
<section id="section-84" class="slide level2">
<h2></h2>
<p>Seguindo a mesma ideia, o compilador realiza o <span class="alert">unboxing</span> quando obtemos um valor da coleção:</p>
<div class="halfincfontsize">
<div class="sourceCode" id="cb25"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb25-1"><a aria-hidden="true" tabindex="-1"></a>    <span class="dt">int</span> primeiraNota <span class="op">=</span> notas<span class="op">.</span><span class="fu">get</span><span class="op">(</span><span class="dv">0</span><span class="op">);</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<p>Veja portanto que, em termos práticos, a única coisa que precisamos lembrar é de declarar o <code>ArrayList</code> usando a classe empacotadora (como a <code>Integer</code>).</p>
<ul>
<li class="fragment">Mas na hora de usar o <code>ArrayList</code> podemos tratar todos os dados como se fossem do tipo <code>int</code>.</li>
</ul>
</div>
</section>
<section id="section-85" class="slide level2">
<h2></h2>
<p>Veja no <strong>Apêndice B do livro</strong> uma lista completa dos tipos primitivos e suas classes empacotadoras.</p>
<ul>
<li class="fragment">Vale ressaltar também que o mesmo conceito é aplicado para as demais coleções, como a classe <code>HashMap</code>.</li>
</ul>
<div class="fragment">
<div title="Conceito">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Conceito</strong></p>
</div>
<div class="callout-content">
<p><strong>Autoboxing</strong> é realizado automaticamente quando um valor de tipo primitivo é usado em um contexto que requer um tipo empacotador (<em>wrapper</em>).</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="fazendo-contabilidade-de-uso-de-objetos" class="slide level2">
<h2>Fazendo contabilidade de uso de objetos</h2>
<p>Combinando um mapa com <em>autoboxing</em>, conseguimos uma maneira simples de contabilizar o uso de objetos.</p>
<div class="fragment">
<p>Suponha, por exemplo, que a empresa responsável pelo Sistema de Suporte queira contar quantas vezes cada palavra não tratada é utilizada.</p>
<ul>
<li class="fragment">Dessa forma, ela poderia identificar palavras muito usadas.</li>
<li class="fragment">E aumentar o seu mapa de respostas para que o usuário seja “melhor” respondido.</li>
</ul>
</div>
</section>
<section id="section-86" class="slide level2">
<h2></h2>
<p>Para isso, vamos criar uma classe <code>ContadorDePalavras</code>.</p>
<ul>
<li class="fragment">A classe vai ter um <code>HashMap</code> que associa da palavra a um contador inteiro.</li>
<li class="fragment">E um método que recebe o <code>HashSet</code> da entrada do usuário e atualiza a contagem das palavras.</li>
</ul>
<div class="fragment">
<p>Vamos usar o método <code>getOrDefault</code> da classe <code>HashMap</code>.</p>
<ul>
<li class="fragment">Esse método é parecido com o <code>get</code>, mas quando a chave não está presente no <code>HashMap</code></li>
<li class="fragment">em vez de retornar <code>null</code>, ele retorna o valor padrão passado como segundo parâmetro do método.</li>
</ul>
</div>
</section>
<section id="section-87" class="slide level2">
<h2></h2>
<div class="sourceCode" id="cb26"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb26-1"><a aria-hidden="true" tabindex="-1"></a><span class="kw">public</span> <span class="kw">class</span> ContadorDePalavras</span>
<span id="cb26-2"><a aria-hidden="true" tabindex="-1"></a><span class="op">{</span></span>
<span id="cb26-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="kw">private</span> <span class="bu">HashMap</span><span class="op">&lt;</span><span class="bu">String</span><span class="op">,</span> <span class="bu">Integer</span><span class="op">&gt;</span> contagem<span class="op">;</span></span>
<span id="cb26-4"><a aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb26-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="kw">public</span> <span class="fu">ContadorDePalavras</span><span class="op">()</span></span>
<span id="cb26-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="op">{</span></span>
<span id="cb26-7"><a aria-hidden="true" tabindex="-1"></a>    contagem <span class="op">=</span> <span class="kw">new</span> <span class="bu">HashMap</span><span class="op">&lt;&gt;();</span></span>
<span id="cb26-8"><a aria-hidden="true" tabindex="-1"></a>  <span class="op">}</span></span>
<span id="cb26-9"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a aria-hidden="true" tabindex="-1"></a>  <span class="kw">public</span> <span class="dt">void</span> <span class="fu">contabilizarPalavras</span><span class="op">(</span><span class="bu">HashSet</span><span class="op">&lt;</span><span class="bu">String</span><span class="op">&gt;</span> entrada<span class="op">)</span></span>
<span id="cb26-11"><a aria-hidden="true" tabindex="-1"></a>  <span class="op">{</span></span>
<span id="cb26-12"><a aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span><span class="op">(</span><span class="bu">String</span> palavra <span class="op">:</span> entrada<span class="op">)</span> <span class="op">{</span></span>
<span id="cb26-13"><a aria-hidden="true" tabindex="-1"></a>        <span class="dt">int</span> contador <span class="op">=</span> contagem<span class="op">.</span><span class="fu">getOrDefault</span><span class="op">(</span>palavra<span class="op">,</span> <span class="dv">0</span><span class="op">);</span></span>
<span id="cb26-14"><a aria-hidden="true" tabindex="-1"></a>        contagem<span class="op">.</span><span class="fu">put</span><span class="op">(</span>palavra<span class="op">,</span> contador<span class="op">+</span><span class="dv">1</span><span class="op">);</span></span>
<span id="cb26-15"><a aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span>
<span id="cb26-16"><a aria-hidden="true" tabindex="-1"></a>  <span class="op">}</span></span>
<span id="cb26-17"><a aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="section-88" class="slide level2">
<h2></h2>
<p>Repare que o trecho que usa o método <code>getOrDefault</code>,</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb27-1"><a aria-hidden="true" tabindex="-1"></a>  <span class="dt">int</span> contador <span class="op">=</span> contagem<span class="op">.</span><span class="fu">getOrDefault</span><span class="op">(</span>palavra<span class="op">,</span> <span class="dv">0</span><span class="op">);</span></span>
<span id="cb27-2"><a aria-hidden="true" tabindex="-1"></a>  contagem<span class="op">.</span><span class="fu">put</span><span class="op">(</span>palavra<span class="op">,</span> contador<span class="op">+</span><span class="dv">1</span><span class="op">);</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="fragment">
<p>faz o mesmo que o trecho a seguir, mas de maneira mais prática.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb28-1"><a aria-hidden="true" tabindex="-1"></a>  <span class="bu">Integer</span> contador <span class="op">=</span> contagem<span class="op">.</span><span class="fu">get</span><span class="op">(</span>palavra<span class="op">);</span></span>
<span id="cb28-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> <span class="op">(</span>contador <span class="op">==</span> <span class="kw">null</span><span class="op">)</span> <span class="op">{</span></span>
<span id="cb28-3"><a aria-hidden="true" tabindex="-1"></a>    contagem<span class="op">.</span><span class="fu">put</span><span class="op">(</span>palavra<span class="op">,</span> <span class="dv">1</span><span class="op">);</span></span>
<span id="cb28-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="op">}</span></span>
<span id="cb28-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span> <span class="op">{</span></span>
<span id="cb28-6"><a aria-hidden="true" tabindex="-1"></a>    contagem<span class="op">.</span><span class="fu">put</span><span class="op">(</span>palavra<span class="op">,</span> contador<span class="op">+</span><span class="dv">1</span><span class="op">);</span></span>
<span id="cb28-7"><a aria-hidden="true" tabindex="-1"></a>  <span class="op">}</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section-89" class="slide level2">
<h2></h2>
<div title="Exercício 29">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 29</strong></p>
</div>
<div class="callout-content">
<p>Altere o sistema de suporte para incluir a classe <code>ContadorDePalavras</code>.</p>
<p>A ideia é contabilizar as palavras das interações com o usuário que levaram a uma resposta padrão.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 30">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 30</strong></p>
</div>
<div class="callout-content">
<p>Adicione um método à classe <code>ContadorDePalavras</code> para exibir no terminal a contagem de uso de cada palavra. Chame o método antes da mensagem de despedida ser exibida.</p>
</div>
</div>
</div>
</div>
</div>
<div class="fragment">
<div title="Exercício 31">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercício 31</strong></p>
</div>
<div class="callout-content">
<p>Pesquise para que serve o método <code>putIfAbasent</code> da classe <code>HashMap</code>.</p>
</div>
</div>
</div>
</div>


</div>
</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="imagens/logo_UFLA.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-pointer/pointer.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'pointer': {"key":"q","color":"red","pointerSize":16,"alwaysVisible":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, RevealPointer, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiada");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiada");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>